/*
 * generated by Xtext 2.10.0
 */
package org.emoflon.ame.ide.contentassist.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.emoflon.ame.ide.contentassist.antlr.internal.InternalLanguageParser;

public class LanguageTokenSource extends AbstractIndentationTokenSource {

	public LanguageTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Implement me
		throw new UnsupportedOperationException("Implement me");
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalLanguageParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalLanguageParser.RULE_END;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
