#------------------------------------------------------------
# Generated by LMS Amesim 14.1.0 -  45543-42458 2015.
# From "C:/Dropbox/ES/Software Campus/CAE-Model/HydraulicExcavator.ame" system,
# Created: 05.05.2017 15:12:40
#
# Note: You can copy or modify this file without restriction.
#------------------------------------------------------------



# Initializations

# Import needed modules
import os, sys

if 'ame_apy' not in sys.modules:
   try:
      from ame_apy import *
   except ImportError:
      print 'Unable to import LMS Amesim API module.\nCheck the AME environment variable.'

# Get license and initialize LMS Amesim Python API
AMEInitAPI(False)

# Create new "HydraulicExcavator" system
AMECreateCircuit('HydraulicExcavator')

# Add components

# Add "runstats" component
AMEAddComponent('runstats', 'runstats', (76, 10))

# Rotate and flip the component
AMERotateComponent('runstats')
AMERotateComponent('runstats')
AMERotateComponent('runstats')
AMEMoveComponent('runstats', (76, 10))

# Set "RSTAT" submodel to "runstats" component
AMEChangeSubmodel('runstats', 'RSTAT', r'$AME\submodels')

# Add "elementaryhydraulicprops" component
AMEAddComponent('elementaryhydraulicprops', 'elementaryhydraulicprops', (140, 7))

# Rotate and flip the component
AMERotateComponent('elementaryhydraulicprops')
AMERotateComponent('elementaryhydraulicprops')
AMERotateComponent('elementaryhydraulicprops')
AMEMoveComponent('elementaryhydraulicprops', (140, 7))

# Set "FP04" submodel to "elementaryhydraulicprops" component
AMEChangeSubmodel('elementaryhydraulicprops', 'FP04', r'$AME\libhydr\submodels')

# Add "valve01_1" component
AMEAddComponent('valve01', 'valve01_1', (861, 668))

# Set "SV00" submodel to "valve01_1" component
AMEChangeSubmodel('valve01_1', 'SV00', r'$AME\libhydr\submodels')

# Add "tank01" component
AMEAddComponent('tank01', 'tank01', (947, 761))

# Set "TK000" submodel to "tank01" component
AMEChangeSubmodel('tank01', 'TK000', r'$AME\libhydr\submodels')

# Add "pressuresource" component
AMEAddComponent('pressuresource', 'pressuresource', (901, 746))

# Set "PS00" submodel to "pressuresource" component
AMEChangeSubmodel('pressuresource', 'PS00', r'$AME\libhydr\submodels')

# Add "JACK01" component
AMEAddComponent('actuator001', 'JACK01', (892, 585))

# Rotate and flip the component
AMEFlipComponent('JACK01')
AMEMoveComponent('JACK01', (892, 585))

# Set "HJ020" submodel to "JACK01" component
AMEChangeSubmodel('JACK01', 'HJ020', r'$AME\libhydr\submodels')

# Add "control01" component
AMEAddComponent('control01', 'control01', (708, 681))

# Rotate and flip the component
AMERotateComponent('control01')
AMERotateComponent('control01')
AMEFlipComponent('control01')
AMEMoveComponent('control01', (708, 681))

# Set "JUN3M" submodel to "control01" component
AMEChangeSubmodel('control01', 'JUN3M', r'$AME\libsig\submodels')

# Add "signal03" component
AMEAddComponent('signal03', 'signal03', (668, 684))

# Set "UD00" submodel to "signal03" component
AMEChangeSubmodel('signal03', 'UD00', r'$AME\libsig\submodels')

# Add "pid" component
AMEAddComponent('pid', 'pid', (788, 683))

# Set "PID001" submodel to "pid" component
AMEChangeSubmodel('pid', 'PID001', r'$AME\libsig\submodels')

# Add "elect01" component
AMEAddComponent('elect01', 'elect01', (739, 689))

# Set "GA00" submodel to "elect01" component
AMEChangeSubmodel('elect01', 'GA00', r'$AME\libsig\submodels')

# Add "valve01_2" component
AMEAddComponent('valve01', 'valve01_2', (617, 362))

# Set "SV00" submodel to "valve01_2" component
AMEChangeSubmodel('valve01_2', 'SV00', r'$AME\libhydr\submodels')

# Add "pressuresource_2" component
AMEAddComponent('pressuresource', 'pressuresource_2', (649, 430))

# Set "PS00" submodel to "pressuresource_2" component
AMEChangeSubmodel('pressuresource_2', 'PS00', r'$AME\libhydr\submodels')

# Add "tank01_2" component
AMEAddComponent('tank01', 'tank01_2', (691, 434))

# Set "TK000" submodel to "tank01_2" component
AMEChangeSubmodel('tank01_2', 'TK000', r'$AME\libhydr\submodels')

# Add "JACK02" component
AMEAddComponent('actuator001', 'JACK02', (642, 265))

# Rotate and flip the component
AMEFlipComponent('JACK02')
AMEMoveComponent('JACK02', (642, 265))

# Set "HJ020" submodel to "JACK02" component
AMEChangeSubmodel('JACK02', 'HJ020', r'$AME\libhydr\submodels')

# Add "control01_2" component
AMEAddComponent('control01', 'control01_2', (464, 375))

# Rotate and flip the component
AMERotateComponent('control01_2')
AMERotateComponent('control01_2')
AMEFlipComponent('control01_2')
AMEMoveComponent('control01_2', (464, 375))

# Set "JUN3M" submodel to "control01_2" component
AMEChangeSubmodel('control01_2', 'JUN3M', r'$AME\libsig\submodels')

# Add "signal03_2" component
AMEAddComponent('signal03', 'signal03_2', (424, 378))

# Set "UD00" submodel to "signal03_2" component
AMEChangeSubmodel('signal03_2', 'UD00', r'$AME\libsig\submodels')

# Add "pid_2" component
AMEAddComponent('pid', 'pid_2', (544, 377))

# Set "PID001" submodel to "pid_2" component
AMEChangeSubmodel('pid_2', 'PID001', r'$AME\libsig\submodels')

# Add "elect01_2" component
AMEAddComponent('elect01', 'elect01_2', (495, 383))

# Set "GA00" submodel to "elect01_2" component
AMEChangeSubmodel('elect01_2', 'GA00', r'$AME\libsig\submodels')

# Add "displacementsensor_2" component
AMEAddComponent('displacementsensor', 'displacementsensor_2', (617, 277))

# Rotate and flip the component
AMERotateComponent('displacementsensor_2')
AMERotateComponent('displacementsensor_2')
AMEMoveComponent('displacementsensor_2', (617, 277))

# Set "DT010" submodel to "displacementsensor_2" component
AMEChangeSubmodel('displacementsensor_2', 'DT010', r'$AME\libmec\submodels')

# Add "valve01_3" component
AMEAddComponent('valve01', 'valve01_3', (456, 169))

# Set "SV00" submodel to "valve01_3" component
AMEChangeSubmodel('valve01_3', 'SV00', r'$AME\libhydr\submodels')

# Add "pressuresource_3" component
AMEAddComponent('pressuresource', 'pressuresource_3', (488, 237))

# Set "PS00" submodel to "pressuresource_3" component
AMEChangeSubmodel('pressuresource_3', 'PS00', r'$AME\libhydr\submodels')

# Add "tank01_3" component
AMEAddComponent('tank01', 'tank01_3', (530, 241))

# Set "TK000" submodel to "tank01_3" component
AMEChangeSubmodel('tank01_3', 'TK000', r'$AME\libhydr\submodels')

# Add "control01_3" component
AMEAddComponent('control01', 'control01_3', (303, 182))

# Rotate and flip the component
AMERotateComponent('control01_3')
AMERotateComponent('control01_3')
AMEFlipComponent('control01_3')
AMEMoveComponent('control01_3', (303, 182))

# Set "JUN3M" submodel to "control01_3" component
AMEChangeSubmodel('control01_3', 'JUN3M', r'$AME\libsig\submodels')

# Add "signal03_3" component
AMEAddComponent('signal03', 'signal03_3', (263, 185))

# Set "UD00" submodel to "signal03_3" component
AMEChangeSubmodel('signal03_3', 'UD00', r'$AME\libsig\submodels')

# Add "pid_3" component
AMEAddComponent('pid', 'pid_3', (383, 184))

# Set "PID001" submodel to "pid_3" component
AMEChangeSubmodel('pid_3', 'PID001', r'$AME\libsig\submodels')

# Add "elect01_3" component
AMEAddComponent('elect01', 'elect01_3', (334, 190))

# Set "GA00" submodel to "elect01_3" component
AMEChangeSubmodel('elect01_3', 'GA00', r'$AME\libsig\submodels')

# Add "displacementsensor_3" component
AMEAddComponent('displacementsensor', 'displacementsensor_3', (456, 84))

# Rotate and flip the component
AMERotateComponent('displacementsensor_3')
AMERotateComponent('displacementsensor_3')
AMEMoveComponent('displacementsensor_3', (456, 84))

# Set "DT010" submodel to "displacementsensor_3" component
AMEChangeSubmodel('displacementsensor_3', 'DT010', r'$AME\libmec\submodels')

# Add "JACK03" component
AMEAddComponent('actuator001', 'JACK03', (481, 72))

# Rotate and flip the component
AMEFlipComponent('JACK03')
AMEMoveComponent('JACK03', (481, 72))

# Set "HJ020" submodel to "JACK03" component
AMEChangeSubmodel('JACK03', 'HJ020', r'$AME\libhydr\submodels')

# Add "plmjack_1" component
AMEAddComponent('plmjack', 'plmjack_1', (146, 339))

# Rotate and flip the component
AMEFlipComponent('plmjack_1')
AMEMoveComponent('plmjack_1', (146, 339))

# Set "PLMJ00" submodel to "plmjack_1" component
AMEChangeSubmodel('plmjack_1', 'PLMJ00', r'$AME\libplm\submodels')

# Add "plmjack_4" component
AMEAddComponent('plmjack', 'plmjack_4', (383, 426))

# Rotate and flip the component
AMEFlipComponent('plmjack_4')
AMEMoveComponent('plmjack_4', (383, 426))

# Set "PLMJ00" submodel to "plmjack_4" component
AMEChangeSubmodel('plmjack_4', 'PLMJ00', r'$AME\libplm\submodels')

# Add "plmpivot_1" component
AMEAddComponent('plmpivot', 'plmpivot_1', (357, 554))

# Set "PLMPIV00" submodel to "plmpivot_1" component
AMEChangeSubmodel('plmpivot_1', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "plmpivot_7" component
AMEAddComponent('plmpivot', 'plmpivot_7', (163, 468))

# Set "PLMPIV00" submodel to "plmpivot_7" component
AMEChangeSubmodel('plmpivot_7', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "plmpivot_8" component
AMEAddComponent('plmpivot', 'plmpivot_8', (62, 486))

# Rotate and flip the component
AMERotateComponent('plmpivot_8')
AMEMoveComponent('plmpivot_8', (62, 486))

# Set "PLMPIV00" submodel to "plmpivot_8" component
AMEChangeSubmodel('plmpivot_8', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "plmpivot_9" component
AMEAddComponent('plmpivot', 'plmpivot_9', (62, 604))

# Rotate and flip the component
AMERotateComponent('plmpivot_9')
AMEMoveComponent('plmpivot_9', (62, 604))

# Set "PLMPIV00" submodel to "plmpivot_9" component
AMEChangeSubmodel('plmpivot_9', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "plmpivot_10" component
AMEAddComponent('plmpivot', 'plmpivot_10', (208, 646))

# Set "PLMPIV00" submodel to "plmpivot_10" component
AMEChangeSubmodel('plmpivot_10', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "dynamic_plmbody" component
AMEAddDynamicComponent('dynamic_plmbody', 'dynamic_plmbody', '3,2', (267, 442))

# Add "dynamic_plmbody_2" component
AMEAddDynamicComponent('dynamic_plmbody', 'dynamic_plmbody_2', '3,3', (446, 558))

# Add "plmzer00_1" component
AMEAddComponent('plmzer00', 'plmzer00_1', (430, 578))

# Rotate and flip the component
AMERotateComponent('plmzer00_1')
AMEMoveComponent('plmzer00_1', (430, 578))

# Set "PLMZER00" submodel to "plmzer00_1" component
AMEChangeSubmodel('plmzer00_1', 'PLMZER00', r'$AME\submodels')

# Add "plmzer00_7" component
AMEAddComponent('plmzer00', 'plmzer00_7', (430, 595))

# Rotate and flip the component
AMERotateComponent('plmzer00_7')
AMEMoveComponent('plmzer00_7', (430, 595))

# Set "PLMZER00" submodel to "plmzer00_7" component
AMEChangeSubmodel('plmzer00_7', 'PLMZER00', r'$AME\submodels')

# Add "dynamic_plmbody_3" component
AMEAddDynamicComponent('dynamic_plmbody', 'dynamic_plmbody_3', '2,1', (73, 407))

# Rotate and flip the component
AMERotateComponent('dynamic_plmbody_3')
AMEMoveComponent('dynamic_plmbody_3', (73, 407))

# Add "dynamic_plmbody_4" component
AMEAddDynamicComponent('dynamic_plmbody', 'dynamic_plmbody_4', '1,1', (49, 551))

# Rotate and flip the component
AMERotateComponent('dynamic_plmbody_4')
AMERotateComponent('dynamic_plmbody_4')
AMERotateComponent('dynamic_plmbody_4')
AMEMoveComponent('dynamic_plmbody_4', (49, 551))

# Add "dynamic_plmbody_5" component
AMEAddDynamicComponent('dynamic_plmbody', 'dynamic_plmbody_5', '3,3', (139, 582))

# Rotate and flip the component
AMERotateComponent('dynamic_plmbody_5')
AMEFlipComponent('dynamic_plmbody_5')
AMEMoveComponent('dynamic_plmbody_5', (139, 582))

# Add "plmzer00_8" component
AMEAddComponent('plmzer00', 'plmzer00_8', (142, 621))

# Set "PLMZER00" submodel to "plmzer00_8" component
AMEChangeSubmodel('plmzer00_8', 'PLMZER00', r'$AME\submodels')

# Add "plmzer00_9" component
AMEAddComponent('plmzer00', 'plmzer00_9', (142, 566))

# Rotate and flip the component
AMERotateComponent('plmzer00_9')
AMERotateComponent('plmzer00_9')
AMEMoveComponent('plmzer00_9', (142, 566))

# Set "PLMZER00" submodel to "plmzer00_9" component
AMEChangeSubmodel('plmzer00_9', 'PLMZER00', r'$AME\submodels')

# Add "plmzer00_10" component
AMEAddComponent('plmzer00', 'plmzer00_10', (159, 566))

# Rotate and flip the component
AMERotateComponent('plmzer00_10')
AMERotateComponent('plmzer00_10')
AMEMoveComponent('plmzer00_10', (159, 566))

# Set "PLMZER00" submodel to "plmzer00_10" component
AMEChangeSubmodel('plmzer00_10', 'PLMZER00', r'$AME\submodels')

# Add "plmzer00_11" component
AMEAddComponent('plmzer00', 'plmzer00_11', (176, 566))

# Rotate and flip the component
AMERotateComponent('plmzer00_11')
AMERotateComponent('plmzer00_11')
AMEMoveComponent('plmzer00_11', (176, 566))

# Set "PLMZER00" submodel to "plmzer00_11" component
AMEChangeSubmodel('plmzer00_11', 'PLMZER00', r'$AME\submodels')

# Add "plmjack_5" component
AMEAddComponent('plmjack', 'plmjack_5', (654, 592))

# Rotate and flip the component
AMERotateComponent('plmjack_5')
AMERotateComponent('plmjack_5')
AMERotateComponent('plmjack_5')
AMEFlipComponent('plmjack_5')
AMEMoveComponent('plmjack_5', (654, 592))

# Set "PLMJ00" submodel to "plmjack_5" component
AMEChangeSubmodel('plmjack_5', 'PLMJ00', r'$AME\libplm\submodels')

# Add "plmrefwall_1" component
AMEAddComponent('plmrefwall', 'plmrefwall_1', (661, 655))

# Set "PLMEMB01" submodel to "plmrefwall_1" component
AMEChangeSubmodel('plmrefwall_1', 'PLMEMB01', r'$AME\submodels')

# Add "plmrefwall_3" component
AMEAddComponent('plmrefwall', 'plmrefwall_3', (601, 675))

# Set "PLMEMB01" submodel to "plmrefwall_3" component
AMEChangeSubmodel('plmrefwall_3', 'PLMEMB01', r'$AME\submodels')

# Add "plmpivot_11" component
AMEAddComponent('plmpivot', 'plmpivot_11', (598, 628))

# Rotate and flip the component
AMERotateComponent('plmpivot_11')
AMEMoveComponent('plmpivot_11', (598, 628))

# Set "PLMPIV00" submodel to "plmpivot_11" component
AMEChangeSubmodel('plmpivot_11', 'PLMPIV00', r'$AME\libplm\submodels')

# Add "plmassembly" component
AMEAddComponent('plmassembly', 'plmassembly', (13, 10))

# Set "PLMASSEMBLY" submodel to "plmassembly" component
AMEChangeSubmodel('plmassembly', 'PLMASSEMBLY', r'$AME\libplm\submodels')

# Add "displacementsensor_1" component
AMEAddComponent('displacementsensor', 'displacementsensor_1', (867, 597))

# Rotate and flip the component
AMERotateComponent('displacementsensor_1')
AMERotateComponent('displacementsensor_1')
AMEMoveComponent('displacementsensor_1', (867, 597))

# Set "DT010" submodel to "displacementsensor_1" component
AMEChangeSubmodel('displacementsensor_1', 'DT010', r'$AME\libmec\submodels')

# Connect "valve01_1" and "pressuresource" with a line
AMEConnectTwoPortsWithLine('valve01_1', 0, 'pressuresource', 0, 'h2port_16', ((921, 731), (913, 731)))

# Connect "valve01_1" and "tank01" with a line
AMEConnectTwoPortsWithLine('tank01', 0, 'valve01_1', 1, 'h2port_15', ((956, 738), (931, 738)))

# Connect "valve01_1" and "JACK01" with a line
AMEConnectTwoPortsWithLine('JACK01', 0, 'valve01_1', 2, 'h2port_18', ((952, 647), (931, 647)))

# Connect "valve01_1" and "JACK01" with a line
AMEConnectTwoPortsWithLine('valve01_1', 3, 'JACK01', 1, 'h2port_17', ((921, 647), (904, 647)))

# Connect "valve01_1" and "pid"
AMEConnectTwoPorts('valve01_1', 4, 'pid', 0)

# Connect "JACK01" and "displacementsensor_1"
AMEConnectTwoPorts('JACK01', 2, 'displacementsensor_1', 2)

# Connect "control01" and "displacementsensor_1" with a line
AMEConnectTwoPortsWithLine('displacementsensor_1', 1, 'control01', 0, 'control', ((879, 663), (723, 663)))

# Connect "control01" and "elect01"
AMEConnectTwoPorts('control01', 1, 'elect01', 1)

# Connect "control01" and "signal03"
AMEConnectTwoPorts('control01', 2, 'signal03', 0)

# Connect "pid" and "elect01"
AMEConnectTwoPorts('pid', 1, 'elect01', 0)

# Connect "valve01_2" and "pressuresource_2" with a line
AMEConnectTwoPortsWithLine('pressuresource_2', 0, 'valve01_2', 0, 'h2port_21', ((661, 420), (677, 420)))

# Connect "valve01_2" and "tank01_2" with a line
AMEConnectTwoPortsWithLine('valve01_2', 1, 'tank01_2', 0, 'h2port_22', ((687, 422), (700, 422)))

# Connect "valve01_2" and "JACK02" with a line
AMEConnectTwoPortsWithLine('JACK02', 0, 'valve01_2', 2, 'h2port_24', ((702, 325), (687, 325)))

# Connect "valve01_2" and "JACK02" with a line
AMEConnectTwoPortsWithLine('JACK02', 1, 'valve01_2', 3, 'h2port_23', ((654, 326), (677, 326)))

# Connect "valve01_2" and "pid_2"
AMEConnectTwoPorts('valve01_2', 4, 'pid_2', 0)

# Connect "JACK02" and "displacementsensor_2"
AMEConnectTwoPorts('JACK02', 2, 'displacementsensor_2', 2)

# Connect "control01_2" and "displacementsensor_2" with a line
AMEConnectTwoPortsWithLine('displacementsensor_2', 1, 'control01_2', 0, 'h2port_32', ((629, 345), (479, 345)))

# Connect "control01_2" and "elect01_2"
AMEConnectTwoPorts('control01_2', 1, 'elect01_2', 1)

# Connect "control01_2" and "signal03_2"
AMEConnectTwoPorts('control01_2', 2, 'signal03_2', 0)

# Connect "pid_2" and "elect01_2"
AMEConnectTwoPorts('pid_2', 1, 'elect01_2', 0)

# Connect "displacementsensor_2" and "plmjack_4" with a line
AMEConnectTwoPortsWithLine('displacementsensor_2', 0, 'plmjack_4', 1, 'h2port_25', ((414, 289)))

# Connect "valve01_3" and "pressuresource_3" with a line
AMEConnectTwoPortsWithLine('pressuresource_3', 0, 'valve01_3', 0, 'h2port_27', ((500, 227), (516, 227)))

# Connect "valve01_3" and "tank01_3" with a line
AMEConnectTwoPortsWithLine('valve01_3', 1, 'tank01_3', 0, 'h2port_28', ((526, 229), (539, 229)))

# Connect "valve01_3" and "JACK03" with a line
AMEConnectTwoPortsWithLine('valve01_3', 2, 'JACK03', 0, 'h2port_30', ((526, 144), (541, 144)))

# Connect "valve01_3" and "JACK03" with a line
AMEConnectTwoPortsWithLine('JACK03', 1, 'valve01_3', 3, 'h2port_29', ((493, 144), (516, 144)))

# Connect "valve01_3" and "pid_3"
AMEConnectTwoPorts('valve01_3', 4, 'pid_3', 0)

# Connect "control01_3" and "displacementsensor_3" with a line
AMEConnectTwoPortsWithLine('displacementsensor_3', 1, 'control01_3', 0, 'h2port_31', ((468, 138), (318, 138)))

# Connect "control01_3" and "elect01_3"
AMEConnectTwoPorts('control01_3', 1, 'elect01_3', 1)

# Connect "control01_3" and "signal03_3"
AMEConnectTwoPorts('control01_3', 2, 'signal03_3', 0)

# Connect "pid_3" and "elect01_3"
AMEConnectTwoPorts('pid_3', 1, 'elect01_3', 0)

# Connect "displacementsensor_3" and "plmjack_1" with a line
AMEConnectTwoPortsWithLine('displacementsensor_3', 0, 'plmjack_1', 1, 'h2port_26', ((177, 96)))

# Connect "displacementsensor_3" and "JACK03"
AMEConnectTwoPorts('displacementsensor_3', 2, 'JACK03', 2)

# Connect "plmjack_1" and "dynamic_plmbody_3" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody_3', 2, 'plmjack_1', 0, 'h2port_48', ((99, 363)))

# Connect "plmjack_1" and "dynamic_plmbody" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody', 3, 'plmjack_1', 2, 'h2port_47', ((242, 454), (242, 363)))

# Connect "plmjack_4" and "dynamic_plmbody" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody', 2, 'plmjack_4', 0, 'h2port_46', ())

# Connect "plmjack_4" and "dynamic_plmbody_2" with a line
AMEConnectTwoPortsWithLine('plmjack_4', 2, 'dynamic_plmbody_2', 2, 'h2port_45', ((533, 450), (533, 566)))

# Connect "plmpivot_1" and "dynamic_plmbody_2" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody_2', 3, 'plmpivot_1', 0, 'h2port_34', ())

# Connect "plmpivot_1" and "dynamic_plmbody" with a line
AMEConnectTwoPortsWithLine('plmpivot_1', 1, 'dynamic_plmbody', 1, 'h2port_35', ((338, 566), (338, 467)))

# Connect "plmpivot_7" and "dynamic_plmbody" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody', 4, 'plmpivot_7', 0, 'h2port_42', ())

# Connect "plmpivot_7" and "dynamic_plmbody_3" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody_3', 1, 'plmpivot_7', 1, 'h2port_36', ((112, 480)))

# Connect "plmpivot_8" and "dynamic_plmbody_4" with a line
AMEConnectTwoPortsWithLine('plmpivot_8', 0, 'dynamic_plmbody_4', 0, 'h2port_37', ())

# Connect "plmpivot_8" and "dynamic_plmbody_3" with a line
AMEConnectTwoPortsWithLine('plmpivot_8', 1, 'dynamic_plmbody_3', 0, 'h2port_43', ((74, 468), (86, 468)))

# Connect "plmpivot_9" and "dynamic_plmbody_5" with a line
AMEConnectTwoPortsWithLine('plmpivot_9', 0, 'dynamic_plmbody_5', 1, 'h2port_40', ((74, 658), (164, 658)))

# Connect "plmpivot_9" and "dynamic_plmbody_4" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody_4', 1, 'plmpivot_9', 1, 'h2port_38', ())

# Connect "plmpivot_10" and "dynamic_plmbody" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody', 0, 'plmpivot_10', 0, 'h2port_41', ((316, 484), (316, 658)))

# Connect "plmpivot_10" and "dynamic_plmbody_5" with a line
AMEConnectTwoPortsWithLine('plmpivot_10', 1, 'dynamic_plmbody_5', 0, 'h2port_39', ((181, 658)))

# Connect "dynamic_plmbody_2" and "plmpivot_11" with a line
AMEConnectTwoPortsWithLine('dynamic_plmbody_2', 0, 'plmpivot_11', 1, 'h2port_1', ((610, 600)))

# Connect "dynamic_plmbody_2" and "plmjack_5" with a line
AMEConnectTwoPortsWithLine('plmjack_5', 0, 'dynamic_plmbody_2', 1, 'h2port_44', ((670, 583)))

# Connect "dynamic_plmbody_2" and "plmzer00_1"
AMEConnectTwoPorts('dynamic_plmbody_2', 4, 'plmzer00_1', 0)

# Connect "dynamic_plmbody_2" and "plmzer00_7"
AMEConnectTwoPorts('dynamic_plmbody_2', 5, 'plmzer00_7', 0)

# Connect "dynamic_plmbody_5" and "plmzer00_8"
AMEConnectTwoPorts('dynamic_plmbody_5', 2, 'plmzer00_8', 0)

# Connect "dynamic_plmbody_5" and "plmzer00_9"
AMEConnectTwoPorts('dynamic_plmbody_5', 3, 'plmzer00_9', 0)

# Connect "dynamic_plmbody_5" and "plmzer00_10"
AMEConnectTwoPorts('dynamic_plmbody_5', 4, 'plmzer00_10', 0)

# Connect "dynamic_plmbody_5" and "plmzer00_11"
AMEConnectTwoPorts('dynamic_plmbody_5', 5, 'plmzer00_11', 0)

# Connect "plmjack_5" and "displacementsensor_1" with a line
AMEConnectTwoPortsWithLine('displacementsensor_1', 0, 'plmjack_5', 1, 'linear', ((781, 609), (781, 623)))

# Connect "plmjack_5" and "plmrefwall_1"
AMEConnectTwoPorts('plmjack_5', 2, 'plmrefwall_1', 0)

# Connect "plmrefwall_3" and "plmpivot_11"
AMEConnectTwoPorts('plmrefwall_3', 0, 'plmpivot_11', 0)

# Add global parameters
AMEAddGlobalParameter('x01', 'initial reference for cylinder 1', 'ame_real_parameter', '1.11', '0.0', '    -1.00000000000000e+06', '     1.00000000000000e+06', 'm')
AMEAddGlobalParameter('x02', 'initial reference for cylinder 2', 'ame_real_parameter', '0.39', '0.0', '    -1.00000000000000e+06', '     1.00000000000000e+06', 'm')
AMEAddGlobalParameter('x03', 'initial reference for cylinder 3', 'ame_real_parameter', '1.35', '0.0', '    -1.00000000000000e+06', '     1.00000000000000e+06', 'm')

# Set 'runstats' parameters

# Set 'elementaryhydraulicprops' parameters
AMESetParameterValue('fpd@elementaryhydraulicprops', '8.50000000000000e+02')
AMESetParameterValue('fpbm@elementaryhydraulicprops', '1.70000000000000e+04')
AMESetParameterValue('fpslope@elementaryhydraulicprops', '0.00000000000000e+00')
AMESetParameterValue('fpav@elementaryhydraulicprops', '5.10000000000000e+01')
AMESetParameterValue('fpavag@elementaryhydraulicprops', '2.00000000000000e-02')
AMESetParameterValue('fpsp@elementaryhydraulicprops', '0.00000000000000e+00')
AMESetParameterValue('fpac@elementaryhydraulicprops', '1.00000000000000e-01')
AMESetParameterValue('fpt@elementaryhydraulicprops', '4.00000000000000e+01')
AMESetParameterValue('T1@elementaryhydraulicprops', '4.00000000000000e+01')
AMESetParameterValue('nu1@elementaryhydraulicprops', '5.64700000000000e+01')
AMESetParameterValue('T2@elementaryhydraulicprops', '1.00000000000000e+02')
AMESetParameterValue('nu2@elementaryhydraulicprops', '9.71000000000000e+00')
AMESetParameterValue('tvis@elementaryhydraulicprops', '8.00000000000000e-01')
AMESetParameterValue('fppi@elementaryhydraulicprops', '1.40000000000000e+00')
AMESetParameterValue('hsvp@elementaryhydraulicprops', '-5.00000000000000e-01')
AMESetParameterValue('lsvp@elementaryhydraulicprops', '-6.00000000000000e-01')
AMESetParameterValue('muvap@elementaryhydraulicprops', '2.00000000000000e-02')
AMESetParameterValue('emm@elementaryhydraulicprops', '2.00000000000000e+02')
AMESetParameterValue('gdens@elementaryhydraulicprops', '1.20000000000000e+00')
AMESetParameterValue('psat@elementaryhydraulicprops', '0.00000000000000e+00')
AMESetParameterValue('proptype@elementaryhydraulicprops', '2')
AMESetParameterValue('rbtype@elementaryhydraulicprops', '3')
AMESetParameterValue('fluidfile@elementaryhydraulicprops', '1')
AMESetParameterValue('bulkmod@elementaryhydraulicprops', '1')
AMESetParameterValue('indexf@elementaryhydraulicprops', '0')
AMESetParameterValue('fluidname@elementaryhydraulicprops', 'unnamed fluid')
AMESetParameterValue('fpfname@elementaryhydraulicprops', '$AME/tutorial/tblprop1.txt')

# Set 'valve01_1' parameters
AMESetParameterValue('x@valve01_1', '0.00000000000000e+000')
AMESetParameterValue('v@valve01_1', '0.00000000000000e+000')
AMESetParameterValue('actRservo@valve01_1', '0.00000000000000e+000')
AMESetParameterValue('energyRservo@valve01_1', '0.00000000000000e+000')
AMESetParameterValue('qpa@valve01_1', '500*1.2')
AMESetParameterValue('ppa@valve01_1', '2.00000000000000e+01')
AMESetParameterValue('lcpa@valve01_1', '1.00000000000000e+03')
AMESetParameterValue('qbt@valve01_1', '500*1.2')
AMESetParameterValue('pbt@valve01_1', '2.00000000000000e+01')
AMESetParameterValue('lcbt@valve01_1', '1.00000000000000e+03')
AMESetParameterValue('qpb@valve01_1', '500*1.2')
AMESetParameterValue('ppb@valve01_1', '2.00000000000000e+01')
AMESetParameterValue('lcpb@valve01_1', '1.00000000000000e+03')
AMESetParameterValue('qat@valve01_1', '500*1.2')
AMESetParameterValue('pat@valve01_1', '2.00000000000000e+01')
AMESetParameterValue('lcat@valve01_1', '1.00000000000000e+03')
AMESetParameterValue('rhochar@valve01_1', '8.50000000000000e+02')
AMESetParameterValue('nuchar@valve01_1', '6.00000000000000e+01')
AMESetParameterValue('irate@valve01_1', '1.00000000000000e+00')
AMESetParameterValue('wn@valve01_1', '8.00000000000000e+01')
AMESetParameterValue('zeta@valve01_1', '8.00000000000000e-01')
AMESetParameterValue('dband@valve01_1', '0.00000000000000e+00')
AMESetParameterValue('indexf@valve01_1', '0')
AMESetParameterValue('userfp@valve01_1', '1')

# Set 'tank01' parameters
AMESetParameterValue('press@tank01', '1.00000000000000e+000')

# Set 'pressuresource' parameters
AMESetParameterValue('tinit@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('ps1@pressuresource', '2.00000000000000e+02')
AMESetParameterValue('pe1@pressuresource', '2.00000000000000e+02')
AMESetParameterValue('dt1@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps2@pressuresource', '3.00000000000000e+02')
AMESetParameterValue('pe2@pressuresource', '3.00000000000000e+02')
AMESetParameterValue('dt2@pressuresource', '1.00000000000000e+01')
AMESetParameterValue('ps3@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe3@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt3@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps4@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe4@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt4@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps5@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe5@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt5@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps6@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe6@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt6@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps7@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe7@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt7@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('ps8@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('pe8@pressuresource', '0.00000000000000e+00')
AMESetParameterValue('dt8@pressuresource', '1.00000000000000e+06')
AMESetParameterValue('nstages@pressuresource', '1')
AMESetParameterValue('iscyclic@pressuresource', '1')

# Set 'JACK01' parameters
AMESetParameterValue('p1@JACK01', '1.89382000000000e+002')
AMESetParameterValue('p2@JACK01', '1.51336000000000e+002')
AMESetParameterValue('actRleak@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energyRleak@JACK01', '0.00000000000000e+000')
AMESetParameterValue('actCchamber1@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber1@JACK01', '0.00000000000000e+000')
AMESetParameterValue('actCchamber2@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber2@JACK01', '0.00000000000000e+000')
AMESetParameterValue('actRfrict@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energyRfrict@JACK01', '0.00000000000000e+000')
AMESetParameterValue('actCendstop@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energyCendstop@JACK01', '0.00000000000000e+000')
AMESetParameterValue('actSpatm@JACK01', '0.00000000000000e+000')
AMESetParameterValue('energySpatm@JACK01', '0.00000000000000e+000')
AMESetParameterValue('xact0@JACK01', '1.04000000000000e+00')
AMESetParameterValue('diamp@JACK01', '3.50000000000000e+02')
AMESetParameterValue('diamr@JACK01', '2.20000000000000e+02')
AMESetParameterValue('stroke@JACK01', '1.80000000000000e+00')
AMESetParameterValue('dead1@JACK01', '5.00000000000000e+01')
AMESetParameterValue('dead2@JACK01', '5.00000000000000e+01')
AMESetParameterValue('visc@JACK01', '1.00000000000000e+05')
AMESetParameterValue('leak@JACK01', '0.05*0')
AMESetParameterValue('k@JACK01', '1.00000000000000e+06')
AMESetParameterValue('cdamp@JACK01', '9.00000000000000e+06')
AMESetParameterValue('distdef@JACK01', '1.00000000000000e-03')
AMESetParameterValue('indexf@JACK01', '0')
AMESetParameterValue('usedispl@JACK01', '1')

# Set 'control01' parameters

# Set 'signal03' parameters
AMESetParameterValue('rp2@signal03', '0.00000000000000e+00')
AMESetParameterValue('rp3@signal03', 'x01')
AMESetParameterValue('rp4@signal03', 'x01')
AMESetParameterValue('rp5@signal03', '2.00000000000000e+00')
AMESetParameterValue('rp6@signal03', 'x01')
AMESetParameterValue('rp7@signal03', 'x01-0.5')
AMESetParameterValue('rp8@signal03', '8.00000000000000e+00')
AMESetParameterValue('rp9@signal03', 'x01-0.5')
AMESetParameterValue('rp10@signal03', 'x01-0.5')
AMESetParameterValue('rp11@signal03', '1.00000000000000e+01')
AMESetParameterValue('rp12@signal03', 'x01-0.5')
AMESetParameterValue('rp13@signal03', 'x01+0.6')
AMESetParameterValue('rp14@signal03', '1.60000000000000e+01')
AMESetParameterValue('rp15@signal03', 'x01+0.6')
AMESetParameterValue('rp16@signal03', 'x01+0.6')
AMESetParameterValue('rp17@signal03', '4.00000000000000e+00')
AMESetParameterValue('rp18@signal03', 'x01+0.6')
AMESetParameterValue('rp19@signal03', 'x01')
AMESetParameterValue('rp20@signal03', '8.00000000000000e+00')
AMESetParameterValue('rp21@signal03', 'x01')
AMESetParameterValue('rp22@signal03', 'x01')
AMESetParameterValue('rp23@signal03', '1.00000000000000e+06')
AMESetParameterValue('rp24@signal03', '0.00000000000000e+00')
AMESetParameterValue('rp25@signal03', '0.00000000000000e+00')
AMESetParameterValue('rp26@signal03', '1.00000000000000e+06')
AMESetParameterValue('nstages@signal03', '7')
AMESetParameterValue('iscyclic@signal03', '1')

# Set 'pid' parameters
AMESetParameterValue('outputtype@pid', '1')
AMESetParameterValue('outlim@pid', '1')
AMESetParameterValue('w@pid', '0.00000000000000e+000')
AMESetParameterValue('ipart@pid', '0.00000000000000e+000')
AMESetParameterValue('Kp@pid', '4.00000000000000e+00')
AMESetParameterValue('Ki@pid', '5.00000000000000e-02')
AMESetParameterValue('Kd@pid', '0.00000000000000e+00')
AMESetParameterValue('tau@pid', '1.00000000000000e-03')
AMESetParameterValue('outmin@pid', '0.00000000000000e+00')
AMESetParameterValue('outmax@pid', '0.00000000000000e+00')
AMESetParameterValue('Ks@pid', '0.00000000000000e+00')
AMESetParameterValue('antiwind@pid', '1')

# Set 'elect01' parameters
AMESetParameterValue('k@elect01', '-1.00000000000000e+00')

# Set 'valve01_2' parameters
AMESetParameterValue('x@valve01_2', '0.00000000000000e+000')
AMESetParameterValue('v@valve01_2', '0.00000000000000e+000')
AMESetParameterValue('actRservo@valve01_2', '0.00000000000000e+000')
AMESetParameterValue('energyRservo@valve01_2', '0.00000000000000e+000')
AMESetParameterValue('qpa@valve01_2', '5.00000000000000e+02')
AMESetParameterValue('ppa@valve01_2', '2.00000000000000e+01')
AMESetParameterValue('lcpa@valve01_2', '1.00000000000000e+03')
AMESetParameterValue('qbt@valve01_2', '5.00000000000000e+02')
AMESetParameterValue('pbt@valve01_2', '2.00000000000000e+01')
AMESetParameterValue('lcbt@valve01_2', '1.00000000000000e+03')
AMESetParameterValue('qpb@valve01_2', '5.00000000000000e+02')
AMESetParameterValue('ppb@valve01_2', '2.00000000000000e+01')
AMESetParameterValue('lcpb@valve01_2', '1.00000000000000e+03')
AMESetParameterValue('qat@valve01_2', '5.00000000000000e+02')
AMESetParameterValue('pat@valve01_2', '2.00000000000000e+01')
AMESetParameterValue('lcat@valve01_2', '1.00000000000000e+03')
AMESetParameterValue('rhochar@valve01_2', '8.50000000000000e+02')
AMESetParameterValue('nuchar@valve01_2', '6.00000000000000e+01')
AMESetParameterValue('irate@valve01_2', '1.00000000000000e+00')
AMESetParameterValue('wn@valve01_2', '8.00000000000000e+01')
AMESetParameterValue('zeta@valve01_2', '8.00000000000000e-01')
AMESetParameterValue('dband@valve01_2', '0.00000000000000e+00')
AMESetParameterValue('indexf@valve01_2', '0')
AMESetParameterValue('userfp@valve01_2', '1')

# Set 'pressuresource_2' parameters
AMESetParameterValue('tinit@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('ps1@pressuresource_2', '2.00000000000000e+02')
AMESetParameterValue('pe1@pressuresource_2', '2.00000000000000e+02')
AMESetParameterValue('dt1@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps2@pressuresource_2', '3.00000000000000e+02')
AMESetParameterValue('pe2@pressuresource_2', '3.00000000000000e+02')
AMESetParameterValue('dt2@pressuresource_2', '1.00000000000000e+01')
AMESetParameterValue('ps3@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe3@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt3@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps4@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe4@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt4@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps5@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe5@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt5@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps6@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe6@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt6@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps7@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe7@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt7@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('ps8@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('pe8@pressuresource_2', '0.00000000000000e+00')
AMESetParameterValue('dt8@pressuresource_2', '1.00000000000000e+06')
AMESetParameterValue('nstages@pressuresource_2', '1')
AMESetParameterValue('iscyclic@pressuresource_2', '1')

# Set 'tank01_2' parameters
AMESetParameterValue('press@tank01_2', '1.00000000000000e+000')

# Set 'JACK02' parameters
AMESetParameterValue('p1@JACK02', '2.58812000000000e+001')
AMESetParameterValue('p2@JACK02', '1.69745000000000e+002')
AMESetParameterValue('actRleak@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energyRleak@JACK02', '0.00000000000000e+000')
AMESetParameterValue('actCchamber1@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber1@JACK02', '0.00000000000000e+000')
AMESetParameterValue('actCchamber2@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber2@JACK02', '0.00000000000000e+000')
AMESetParameterValue('actRfrict@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energyRfrict@JACK02', '0.00000000000000e+000')
AMESetParameterValue('actCendstop@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energyCendstop@JACK02', '0.00000000000000e+000')
AMESetParameterValue('actSpatm@JACK02', '0.00000000000000e+000')
AMESetParameterValue('energySpatm@JACK02', '0.00000000000000e+000')
AMESetParameterValue('xact0@JACK02', '0.00000000000000e+00')
AMESetParameterValue('diamp@JACK02', '1.80000000000000e+02')
AMESetParameterValue('diamr@JACK02', '1.25000000000000e+02')
AMESetParameterValue('stroke@JACK02', '1.70000000000000e+00')
AMESetParameterValue('dead1@JACK02', '5.00000000000000e+01')
AMESetParameterValue('dead2@JACK02', '5.00000000000000e+01')
AMESetParameterValue('visc@JACK02', '1.00000000000000e+05')
AMESetParameterValue('leak@JACK02', '0.05*0')
AMESetParameterValue('k@JACK02', '1.00000000000000e+05')
AMESetParameterValue('cdamp@JACK02', '1.00000000000000e+05')
AMESetParameterValue('distdef@JACK02', '1.00000000000000e-03')
AMESetParameterValue('indexf@JACK02', '0')
AMESetParameterValue('usedispl@JACK02', '1')

# Set 'control01_2' parameters

# Set 'signal03_2' parameters
AMESetParameterValue('rp2@signal03_2', '0.00000000000000e+00')
AMESetParameterValue('rp3@signal03_2', 'x02')
AMESetParameterValue('rp4@signal03_2', 'x02')
AMESetParameterValue('rp5@signal03_2', '2.00000000000000e+00')
AMESetParameterValue('rp6@signal03_2', 'x02')
AMESetParameterValue('rp7@signal03_2', 'x02+1.3')
AMESetParameterValue('rp8@signal03_2', '8.00000000000000e+00')
AMESetParameterValue('rp9@signal03_2', 'x02+1.3')
AMESetParameterValue('rp10@signal03_2', 'x02+1.3')
AMESetParameterValue('rp11@signal03_2', '1.00000000000000e+01')
AMESetParameterValue('rp12@signal03_2', 'x02+1.3')
AMESetParameterValue('rp13@signal03_2', 'x02-0.35')
AMESetParameterValue('rp14@signal03_2', '1.60000000000000e+01')
AMESetParameterValue('rp15@signal03_2', 'x02-0.35')
AMESetParameterValue('rp16@signal03_2', 'x02-0.35')
AMESetParameterValue('rp17@signal03_2', '4.00000000000000e+00')
AMESetParameterValue('rp18@signal03_2', 'x02-0.35')
AMESetParameterValue('rp19@signal03_2', 'x02')
AMESetParameterValue('rp20@signal03_2', '6.00000000000000e+00')
AMESetParameterValue('rp21@signal03_2', 'x02')
AMESetParameterValue('rp22@signal03_2', 'x02')
AMESetParameterValue('rp23@signal03_2', '1.00000000000000e+06')
AMESetParameterValue('rp24@signal03_2', '0.00000000000000e+00')
AMESetParameterValue('rp25@signal03_2', '0.00000000000000e+00')
AMESetParameterValue('rp26@signal03_2', '1.00000000000000e+06')
AMESetParameterValue('nstages@signal03_2', '7')
AMESetParameterValue('iscyclic@signal03_2', '1')

# Set 'pid_2' parameters
AMESetParameterValue('outputtype@pid_2', '1')
AMESetParameterValue('outlim@pid_2', '1')
AMESetParameterValue('w@pid_2', '0.00000000000000e+000')
AMESetParameterValue('ipart@pid_2', '0.00000000000000e+000')
AMESetParameterValue('Kp@pid_2', '4.00000000000000e+00')
AMESetParameterValue('Ki@pid_2', '1.00000000000000e-01')
AMESetParameterValue('Kd@pid_2', '0.00000000000000e+00')
AMESetParameterValue('tau@pid_2', '1.00000000000000e-03')
AMESetParameterValue('outmin@pid_2', '0.00000000000000e+00')
AMESetParameterValue('outmax@pid_2', '0.00000000000000e+00')
AMESetParameterValue('Ks@pid_2', '0.00000000000000e+00')
AMESetParameterValue('antiwind@pid_2', '1')

# Set 'elect01_2' parameters
AMESetParameterValue('k@elect01_2', '-1.00000000000000e+00')

# Set 'displacementsensor_2' parameters
AMESetParameterValue('offset@displacementsensor_2', '0.00000000000000e+00')
AMESetParameterValue('gain@displacementsensor_2', '-1.00000000000000e+00')

# Set 'valve01_3' parameters
AMESetParameterValue('x@valve01_3', '0.00000000000000e+000')
AMESetParameterValue('v@valve01_3', '0.00000000000000e+000')
AMESetParameterValue('actRservo@valve01_3', '0.00000000000000e+000')
AMESetParameterValue('energyRservo@valve01_3', '0.00000000000000e+000')
AMESetParameterValue('qpa@valve01_3', '5.00000000000000e+02')
AMESetParameterValue('ppa@valve01_3', '2.00000000000000e+01')
AMESetParameterValue('lcpa@valve01_3', '1.00000000000000e+03')
AMESetParameterValue('qbt@valve01_3', '5.00000000000000e+02')
AMESetParameterValue('pbt@valve01_3', '2.00000000000000e+01')
AMESetParameterValue('lcbt@valve01_3', '1.00000000000000e+03')
AMESetParameterValue('qpb@valve01_3', '5.00000000000000e+02')
AMESetParameterValue('ppb@valve01_3', '2.00000000000000e+01')
AMESetParameterValue('lcpb@valve01_3', '1.00000000000000e+03')
AMESetParameterValue('qat@valve01_3', '5.00000000000000e+02')
AMESetParameterValue('pat@valve01_3', '2.00000000000000e+01')
AMESetParameterValue('lcat@valve01_3', '1.00000000000000e+03')
AMESetParameterValue('rhochar@valve01_3', '8.50000000000000e+02')
AMESetParameterValue('nuchar@valve01_3', '6.00000000000000e+01')
AMESetParameterValue('irate@valve01_3', '1.00000000000000e+00')
AMESetParameterValue('wn@valve01_3', '8.00000000000000e+01')
AMESetParameterValue('zeta@valve01_3', '8.00000000000000e-01')
AMESetParameterValue('dband@valve01_3', '0.00000000000000e+00')
AMESetParameterValue('indexf@valve01_3', '0')
AMESetParameterValue('userfp@valve01_3', '1')

# Set 'pressuresource_3' parameters
AMESetParameterValue('tinit@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('ps1@pressuresource_3', '2.00000000000000e+02')
AMESetParameterValue('pe1@pressuresource_3', '2.00000000000000e+02')
AMESetParameterValue('dt1@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps2@pressuresource_3', '3.00000000000000e+02')
AMESetParameterValue('pe2@pressuresource_3', '3.00000000000000e+02')
AMESetParameterValue('dt2@pressuresource_3', '1.00000000000000e+01')
AMESetParameterValue('ps3@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe3@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt3@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps4@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe4@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt4@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps5@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe5@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt5@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps6@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe6@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt6@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps7@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe7@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt7@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('ps8@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('pe8@pressuresource_3', '0.00000000000000e+00')
AMESetParameterValue('dt8@pressuresource_3', '1.00000000000000e+06')
AMESetParameterValue('nstages@pressuresource_3', '1')
AMESetParameterValue('iscyclic@pressuresource_3', '1')

# Set 'tank01_3' parameters
AMESetParameterValue('press@tank01_3', '1.00000000000000e+000')

# Set 'control01_3' parameters

# Set 'signal03_3' parameters
AMESetParameterValue('rp2@signal03_3', '0.00000000000000e+00')
AMESetParameterValue('rp3@signal03_3', 'x03')
AMESetParameterValue('rp4@signal03_3', 'x03')
AMESetParameterValue('rp5@signal03_3', '5.00000000000000e-01')
AMESetParameterValue('rp6@signal03_3', 'x03')
AMESetParameterValue('rp7@signal03_3', 'x03-1.3')
AMESetParameterValue('rp8@signal03_3', '8.00000000000000e+00')
AMESetParameterValue('rp9@signal03_3', 'x03-1.3')
AMESetParameterValue('rp10@signal03_3', 'x03-1.3')
AMESetParameterValue('rp11@signal03_3', '4.00000000000000e+00')
AMESetParameterValue('rp12@signal03_3', 'x03-1.3')
AMESetParameterValue('rp13@signal03_3', 'x03+0.1')
AMESetParameterValue('rp14@signal03_3', '1.20000000000000e+01')
AMESetParameterValue('rp15@signal03_3', 'x03+0.1')
AMESetParameterValue('rp16@signal03_3', 'x03+0.1')
AMESetParameterValue('rp17@signal03_3', '2.00000000000000e+00')
AMESetParameterValue('rp18@signal03_3', 'x03+0.1')
AMESetParameterValue('rp19@signal03_3', 'x03+0.1')
AMESetParameterValue('rp20@signal03_3', '5.00000000000000e+00')
AMESetParameterValue('rp21@signal03_3', 'x03+0.1')
AMESetParameterValue('rp22@signal03_3', 'x03-1.3')
AMESetParameterValue('rp23@signal03_3', '1.20000000000000e+01')
AMESetParameterValue('rp24@signal03_3', '0.00000000000000e+00')
AMESetParameterValue('rp25@signal03_3', '0.00000000000000e+00')
AMESetParameterValue('rp26@signal03_3', '1.00000000000000e+06')
AMESetParameterValue('nstages@signal03_3', '8')
AMESetParameterValue('iscyclic@signal03_3', '1')

# Set 'pid_3' parameters
AMESetParameterValue('outputtype@pid_3', '1')
AMESetParameterValue('outlim@pid_3', '1')
AMESetParameterValue('w@pid_3', '0.00000000000000e+000')
AMESetParameterValue('ipart@pid_3', '0.00000000000000e+000')
AMESetParameterValue('Kp@pid_3', '4.00000000000000e+00')
AMESetParameterValue('Ki@pid_3', '1.00000000000000e-01')
AMESetParameterValue('Kd@pid_3', '0.00000000000000e+00')
AMESetParameterValue('tau@pid_3', '1.00000000000000e-03')
AMESetParameterValue('outmin@pid_3', '0.00000000000000e+00')
AMESetParameterValue('outmax@pid_3', '0.00000000000000e+00')
AMESetParameterValue('Ks@pid_3', '0.00000000000000e+00')
AMESetParameterValue('antiwind@pid_3', '1')

# Set 'elect01_3' parameters
AMESetParameterValue('k@elect01_3', '-1.00000000000000e+00')

# Set 'displacementsensor_3' parameters
AMESetParameterValue('offset@displacementsensor_3', '0.00000000000000e+00')
AMESetParameterValue('gain@displacementsensor_3', '-1.00000000000000e+00')

# Set 'JACK03' parameters
AMESetParameterValue('p1@JACK03', '6.17118000000000e+001')
AMESetParameterValue('p2@JACK03', '1.21794000000000e+002')
AMESetParameterValue('actRleak@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energyRleak@JACK03', '0.00000000000000e+000')
AMESetParameterValue('actCchamber1@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber1@JACK03', '0.00000000000000e+000')
AMESetParameterValue('actCchamber2@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energyCchamber2@JACK03', '0.00000000000000e+000')
AMESetParameterValue('actRfrict@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energyRfrict@JACK03', '0.00000000000000e+000')
AMESetParameterValue('actCendstop@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energyCendstop@JACK03', '0.00000000000000e+000')
AMESetParameterValue('actSpatm@JACK03', '0.00000000000000e+000')
AMESetParameterValue('energySpatm@JACK03', '0.00000000000000e+000')
AMESetParameterValue('xact0@JACK03', '0.00000000000000e+00')
AMESetParameterValue('diamp@JACK03', '2.10000000000000e+02')
AMESetParameterValue('diamr@JACK03', '1.30000000000000e+02')
AMESetParameterValue('stroke@JACK03', '1.33000000000000e+00')
AMESetParameterValue('dead1@JACK03', '5.00000000000000e+01')
AMESetParameterValue('dead2@JACK03', '5.00000000000000e+01')
AMESetParameterValue('visc@JACK03', '1.00000000000000e+05')
AMESetParameterValue('leak@JACK03', '0.05*0')
AMESetParameterValue('k@JACK03', '1.00000000000000e+06')
AMESetParameterValue('cdamp@JACK03', '1.00000000000000e+05')
AMESetParameterValue('distdef@JACK03', '1.00000000000000e-03')
AMESetParameterValue('indexf@JACK03', '0')
AMESetParameterValue('usedispl@JACK03', '1')

# Set 'plmjack_1' parameters
AMESetParameterValue('T1@plmjack_1', '0.00000000000000e+000')
AMESetParameterValue('T3@plmjack_1', '0.00000000000000e+000')
AMESetParameterValue('x0@plmjack_1', '2.35000000000000e+00')
AMESetParameterValue('pd@plmjack_1', '2.10000000000000e-01')
AMESetParameterValue('dr@plmjack_1', '1.40000000000000e-01')

# Set 'plmjack_4' parameters
AMESetParameterValue('T1@plmjack_4', '0.00000000000000e+000')
AMESetParameterValue('T3@plmjack_4', '0.00000000000000e+000')
AMESetParameterValue('x0@plmjack_4', '2.40000000000000e+00')
AMESetParameterValue('pd@plmjack_4', '1.80000000000000e-01')
AMESetParameterValue('dr@plmjack_4', '1.25000000000000e-01')

# Set 'plmpivot_1' parameters
AMESetParameterValue('Fx1@plmpivot_1', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_1', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_1', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_1', '1.00000000000000e+04')
AMESetParameterValue('dpin@plmpivot_1', '0.00000000000000e+00')

# Set 'plmpivot_7' parameters
AMESetParameterValue('Fx1@plmpivot_7', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_7', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_7', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_7', '1.00000000000000e+04')
AMESetParameterValue('dpin@plmpivot_7', '0.00000000000000e+00')

# Set 'plmpivot_8' parameters
AMESetParameterValue('Fx1@plmpivot_8', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_8', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_8', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_8', '1.00000000000000e+00')
AMESetParameterValue('dpin@plmpivot_8', '0.00000000000000e+00')

# Set 'plmpivot_9' parameters
AMESetParameterValue('Fx1@plmpivot_9', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_9', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_9', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_9', '1.00000000000000e+00')
AMESetParameterValue('dpin@plmpivot_9', '0.00000000000000e+00')

# Set 'plmpivot_10' parameters
AMESetParameterValue('Fx1@plmpivot_10', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_10', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_10', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_10', '1.00000000000000e+04')
AMESetParameterValue('dpin@plmpivot_10', '0.00000000000000e+00')

# Set 'dynamic_plmbody' parameters
AMESetParameterValue('theta@dynamic_plmbody', '3.75000000000000e+001')
AMESetParameterValue('omega@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('Gx@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('Gy@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('Gvx@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('Gvy@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('zdepth@dynamic_plmbody', '0.00000000000000e+000')
AMESetParameterValue('thetaini@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('Ox@dynamic_plmbody', '-7.55751000000000e+00')
AMESetParameterValue('Oy@dynamic_plmbody', '1.94341000000000e+00')
AMESetParameterValue('Gxr@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('Gyr@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('xr1@dynamic_plmbody', '-2.28900000000000e+00')
AMESetParameterValue('xr2@dynamic_plmbody', '6.10990000000000e-01')
AMESetParameterValue('xr3@dynamic_plmbody', '1.43900000000000e+00')
AMESetParameterValue('xr4@dynamic_plmbody', '1.04600000000000e+00')
AMESetParameterValue('xr5@dynamic_plmbody', '-1.77400000000000e+00')
AMESetParameterValue('yr1@dynamic_plmbody', '-2.98001000000000e-01')
AMESetParameterValue('yr2@dynamic_plmbody', '-2.98001000000000e-01')
AMESetParameterValue('yr3@dynamic_plmbody', '3.31999000000000e-01')
AMESetParameterValue('yr4@dynamic_plmbody', '7.36999000000000e-01')
AMESetParameterValue('yr5@dynamic_plmbody', '2.62001000000000e-01')
AMESetParameterValue('alpha1@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('alpha2@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('alpha3@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('alpha4@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('alpha5@dynamic_plmbody', '0.00000000000000e+00')
AMESetParameterValue('m@dynamic_plmbody', '2.92000000000000e+03')
AMESetParameterValue('inerti@dynamic_plmbody', '3.60000000000000e+03')
AMESetParameterValue('findex@dynamic_plmbody', '0')
AMESetParameterValue('usecontour@dynamic_plmbody', '1')
AMESetParameterValue('option@dynamic_plmbody', '1')
AMESetParameterValue('contourname@dynamic_plmbody', 'contour.dat')

# Set 'dynamic_plmbody_2' parameters
AMESetParameterValue('theta@dynamic_plmbody_2', '4.28574000000000e+000')
AMESetParameterValue('omega@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('Gx@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('Gy@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('Gvx@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('Gvy@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('zdepth@dynamic_plmbody_2', '0.00000000000000e+000')
AMESetParameterValue('thetaini@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('Ox@dynamic_plmbody_2', '-2.93901000000000e+00')
AMESetParameterValue('Oy@dynamic_plmbody_2', '1.93090000000000e+00')
AMESetParameterValue('Gxr@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('Gyr@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('xr1@dynamic_plmbody_2', '2.78442000000000e+00')
AMESetParameterValue('xr2@dynamic_plmbody_2', '2.76700000000000e-01')
AMESetParameterValue('xr3@dynamic_plmbody_2', '-7.96000000000000e-01')
AMESetParameterValue('xr4@dynamic_plmbody_2', '-3.93100000000000e+00')
AMESetParameterValue('xr5@dynamic_plmbody_2', '-1.50000000000000e+00')
AMESetParameterValue('xr6@dynamic_plmbody_2', '-2.00000000000000e-01')
AMESetParameterValue('yr1@dynamic_plmbody_2', '-2.14782000000000e+00')
AMESetParameterValue('yr2@dynamic_plmbody_2', '4.49000000000000e-01')
AMESetParameterValue('yr3@dynamic_plmbody_2', '1.23900000000000e+00')
AMESetParameterValue('yr4@dynamic_plmbody_2', '4.49000000000000e-01')
AMESetParameterValue('yr5@dynamic_plmbody_2', '3.00000000000000e-01')
AMESetParameterValue('yr6@dynamic_plmbody_2', '-2.00000000000000e-01')
AMESetParameterValue('alpha1@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('alpha2@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('alpha3@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('alpha4@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('alpha5@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('alpha6@dynamic_plmbody_2', '0.00000000000000e+00')
AMESetParameterValue('m@dynamic_plmbody_2', '8.00000000000000e+03')
AMESetParameterValue('inerti@dynamic_plmbody_2', '3.85000000000000e+04')
AMESetParameterValue('findex@dynamic_plmbody_2', '0')
AMESetParameterValue('usecontour@dynamic_plmbody_2', '1')
AMESetParameterValue('option@dynamic_plmbody_2', '1')
AMESetParameterValue('contourname@dynamic_plmbody_2', 'contour.dat')

# Set 'plmzer00_1' parameters
AMESetParameterValue('RC@plmzer00_1', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_1', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_1', '0.00000000000000e+000')

# Set 'plmzer00_7' parameters
AMESetParameterValue('RC@plmzer00_7', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_7', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_7', '0.00000000000000e+000')

# Set 'dynamic_plmbody_3' parameters
AMESetParameterValue('theta@dynamic_plmbody_3', '-5.71900000000000e+001')
AMESetParameterValue('omega@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('Gx@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('Gy@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('Gvx@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('Gvy@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('zdepth@dynamic_plmbody_3', '0.00000000000000e+000')
AMESetParameterValue('thetaini@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('Ox@dynamic_plmbody_3', '-9.49088000000000e+00')
AMESetParameterValue('Oy@dynamic_plmbody_3', '8.89205000000000e-01')
AMESetParameterValue('Gxr@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('Gyr@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('xr1@dynamic_plmbody_3', '5.50000000000000e-02')
AMESetParameterValue('xr2@dynamic_plmbody_3', '5.50000000000000e-02')
AMESetParameterValue('xr3@dynamic_plmbody_3', '5.50000000000000e-02')
AMESetParameterValue('yr1@dynamic_plmbody_3', '-4.35000000000000e-01')
AMESetParameterValue('yr2@dynamic_plmbody_3', '4.05000000000000e-01')
AMESetParameterValue('yr3@dynamic_plmbody_3', '-4.35000000000000e-01')
AMESetParameterValue('alpha1@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('alpha2@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('alpha3@dynamic_plmbody_3', '0.00000000000000e+00')
AMESetParameterValue('m@dynamic_plmbody_3', '1.68000000000000e+02')
AMESetParameterValue('inerti@dynamic_plmbody_3', '1.00000000000000e+01')
AMESetParameterValue('findex@dynamic_plmbody_3', '0')
AMESetParameterValue('usecontour@dynamic_plmbody_3', '1')
AMESetParameterValue('option@dynamic_plmbody_3', '1')
AMESetParameterValue('contourname@dynamic_plmbody_3', 'contour.dat')

# Set 'dynamic_plmbody_4' parameters
AMESetParameterValue('theta@dynamic_plmbody_4', '9.00000000000000e+001')
AMESetParameterValue('omega@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('Gx@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('Gy@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('Gvx@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('Gvy@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('zdepth@dynamic_plmbody_4', '0.00000000000000e+000')
AMESetParameterValue('thetaini@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('Ox@dynamic_plmbody_4', '-9.84086000000000e+00')
AMESetParameterValue('Oy@dynamic_plmbody_4', '2.03800000000000e-01')
AMESetParameterValue('Gxr@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('Gyr@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('xr1@dynamic_plmbody_4', '4.00000000000000e-01')
AMESetParameterValue('xr2@dynamic_plmbody_4', '-4.00000000000000e-01')
AMESetParameterValue('yr1@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('yr2@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('alpha1@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('alpha2@dynamic_plmbody_4', '0.00000000000000e+00')
AMESetParameterValue('m@dynamic_plmbody_4', '2.25000000000000e+02')
AMESetParameterValue('inerti@dynamic_plmbody_4', '1.30000000000000e+01')
AMESetParameterValue('findex@dynamic_plmbody_4', '0')
AMESetParameterValue('usecontour@dynamic_plmbody_4', '1')
AMESetParameterValue('option@dynamic_plmbody_4', '1')
AMESetParameterValue('contourname@dynamic_plmbody_4', 'contour.dat')

# Set 'dynamic_plmbody_5' parameters
AMESetParameterValue('theta@dynamic_plmbody_5', '1.28475000000000e+002')
AMESetParameterValue('omega@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('Gx@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('Gy@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('Gvx@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('Gvy@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('zdepth@dynamic_plmbody_5', '0.00000000000000e+000')
AMESetParameterValue('thetaini@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('Ox@dynamic_plmbody_5', '-9.16544000000000e+00')
AMESetParameterValue('Oy@dynamic_plmbody_5', '-8.74728000000000e-01')
AMESetParameterValue('Gxr@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('Gyr@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('xr1@dynamic_plmbody_5', '9.28002000000000e-01')
AMESetParameterValue('xr2@dynamic_plmbody_5', '9.28002000000000e-01')
AMESetParameterValue('xr3@dynamic_plmbody_5', '1.00000000000000e-01')
AMESetParameterValue('xr4@dynamic_plmbody_5', '-3.50000000000000e-01')
AMESetParameterValue('xr5@dynamic_plmbody_5', '-9.00000000000000e-01')
AMESetParameterValue('xr6@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('yr1@dynamic_plmbody_5', '-7.32002000000000e-01')
AMESetParameterValue('yr2@dynamic_plmbody_5', '6.79980000000000e-02')
AMESetParameterValue('yr3@dynamic_plmbody_5', '5.00000000000000e-01')
AMESetParameterValue('yr4@dynamic_plmbody_5', '3.50000000000000e-01')
AMESetParameterValue('yr5@dynamic_plmbody_5', '-7.00000000000000e-01')
AMESetParameterValue('yr6@dynamic_plmbody_5', '-4.00000000000000e-01')
AMESetParameterValue('alpha1@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('alpha2@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('alpha3@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('alpha4@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('alpha5@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('alpha6@dynamic_plmbody_5', '0.00000000000000e+00')
AMESetParameterValue('m@dynamic_plmbody_5', '4.93500000000000e+03')
AMESetParameterValue('inerti@dynamic_plmbody_5', '1.90000000000000e+03')
AMESetParameterValue('findex@dynamic_plmbody_5', '0')
AMESetParameterValue('usecontour@dynamic_plmbody_5', '1')
AMESetParameterValue('option@dynamic_plmbody_5', '1')
AMESetParameterValue('contourname@dynamic_plmbody_5', 'contour.dat')

# Set 'plmzer00_8' parameters
AMESetParameterValue('RC@plmzer00_8', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_8', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_8', '0.00000000000000e+000')

# Set 'plmzer00_9' parameters
AMESetParameterValue('RC@plmzer00_9', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_9', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_9', '0.00000000000000e+000')

# Set 'plmzer00_10' parameters
AMESetParameterValue('RC@plmzer00_10', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_10', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_10', '0.00000000000000e+000')

# Set 'plmzer00_11' parameters
AMESetParameterValue('RC@plmzer00_11', '0.00000000000000e+000')
AMESetParameterValue('Fx@plmzer00_11', '0.00000000000000e+000')
AMESetParameterValue('Fy@plmzer00_11', '0.00000000000000e+000')

# Set 'plmjack_5' parameters
AMESetParameterValue('T1@plmjack_5', '0.00000000000000e+000')
AMESetParameterValue('T3@plmjack_5', '0.00000000000000e+000')
AMESetParameterValue('x0@plmjack_5', '2.70000000000000e+00')
AMESetParameterValue('pd@plmjack_5', '2.10000000000000e-01')
AMESetParameterValue('dr@plmjack_5', '1.40000000000000e-01')

# Set 'plmrefwall_1' parameters
AMESetParameterValue('theta@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('xa1@plmrefwall_1', '-9.30000000000000e-001')
AMESetParameterValue('ya1@plmrefwall_1', '-9.75000000000000e-001')
AMESetParameterValue('omega@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('vx1@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('vy1@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('gamma@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('ax1@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('ay1@plmrefwall_1', '0.00000000000000e+000')
AMESetParameterValue('zdepth@plmrefwall_1', '0.00000000000000e+000')

# Set 'plmrefwall_3' parameters
AMESetParameterValue('theta@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('xa1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('ya1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('omega@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('vx1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('vy1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('gamma@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('ax1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('ay1@plmrefwall_3', '0.00000000000000e+000')
AMESetParameterValue('zdepth@plmrefwall_3', '0.00000000000000e+000')

# Set 'plmpivot_11' parameters
AMESetParameterValue('Fx1@plmpivot_11', '0.00000000000000e+000')
AMESetParameterValue('Fy1@plmpivot_11', '0.00000000000000e+000')
AMESetParameterValue('k@plmpivot_11', '0.00000000000000e+00')
AMESetParameterValue('b@plmpivot_11', '1.00000000000000e+04')
AMESetParameterValue('dpin@plmpivot_11', '0.00000000000000e+00')

# Set 'plmassembly' parameters
AMESetParameterValue('wopenenabled@plmassembly', '2')
AMESetParameterValue('wopenmode@plmassembly', '2')
AMESetParameterValue('performassembly@plmassembly', '1')

# Set 'displacementsensor_1' parameters
AMESetParameterValue('offset@displacementsensor_1', '0.00000000000000e+00')
AMESetParameterValue('gain@displacementsensor_1', '-1.00000000000000e+00')

# Set 'h2port_16' parameters

# Set 'h2port_15' parameters

# Set 'h2port_18' parameters

# Set 'h2port_17' parameters

# Set 'h2port_21' parameters

# Set 'h2port_22' parameters

# Set 'h2port_24' parameters

# Set 'h2port_23' parameters

# Set 'h2port_32' parameters

# Set 'h2port_25' parameters

# Set 'h2port_27' parameters

# Set 'h2port_28' parameters

# Set 'h2port_30' parameters

# Set 'h2port_29' parameters

# Set 'h2port_31' parameters

# Set 'h2port_26' parameters

# Set 'h2port_48' parameters

# Set 'h2port_47' parameters

# Set 'h2port_46' parameters

# Set 'h2port_45' parameters

# Set 'h2port_34' parameters

# Set 'h2port_35' parameters

# Set 'h2port_42' parameters

# Set 'h2port_36' parameters

# Set 'h2port_37' parameters

# Set 'h2port_43' parameters

# Set 'h2port_40' parameters

# Set 'h2port_38' parameters

# Set 'h2port_41' parameters

# Set 'h2port_39' parameters

# Set 'h2port_1' parameters

# Set 'h2port_44' parameters

# Set 'control' parameters

# Set 'linear' parameters

# Generate code
AMEGenerateCode()

# Add 'Save next' and 'Lock State' flags
AMESaveVariable('actRservo@valve01_1', False)
AMESaveVariable('powerRservo@valve01_1', False)
AMESaveVariable('energyRservo@valve01_1', False)
AMESaveVariable('actRleak@JACK01', False)
AMESaveVariable('powerRleak@JACK01', False)
AMESaveVariable('energyRleak@JACK01', False)
AMESaveVariable('actCchamber1@JACK01', False)
AMESaveVariable('powerCchamber1@JACK01', False)
AMESaveVariable('energyCchamber1@JACK01', False)
AMESaveVariable('actCchamber2@JACK01', False)
AMESaveVariable('powerCchamber2@JACK01', False)
AMESaveVariable('energyCchamber2@JACK01', False)
AMESaveVariable('actRfrict@JACK01', False)
AMESaveVariable('powerRfrict@JACK01', False)
AMESaveVariable('energyRfrict@JACK01', False)
AMESaveVariable('actCendstop@JACK01', False)
AMESaveVariable('powerCendstop@JACK01', False)
AMESaveVariable('energyCendstop@JACK01', False)
AMESaveVariable('actSpatm@JACK01', False)
AMESaveVariable('powerSpatm@JACK01', False)
AMESaveVariable('energySpatm@JACK01', False)
AMESaveVariable('actRservo@valve01_2', False)
AMESaveVariable('powerRservo@valve01_2', False)
AMESaveVariable('energyRservo@valve01_2', False)
AMESaveVariable('actRleak@JACK02', False)
AMESaveVariable('powerRleak@JACK02', False)
AMESaveVariable('energyRleak@JACK02', False)
AMESaveVariable('actCchamber1@JACK02', False)
AMESaveVariable('powerCchamber1@JACK02', False)
AMESaveVariable('energyCchamber1@JACK02', False)
AMESaveVariable('actCchamber2@JACK02', False)
AMESaveVariable('powerCchamber2@JACK02', False)
AMESaveVariable('energyCchamber2@JACK02', False)
AMESaveVariable('actRfrict@JACK02', False)
AMESaveVariable('powerRfrict@JACK02', False)
AMESaveVariable('energyRfrict@JACK02', False)
AMESaveVariable('actCendstop@JACK02', False)
AMESaveVariable('powerCendstop@JACK02', False)
AMESaveVariable('energyCendstop@JACK02', False)
AMESaveVariable('actSpatm@JACK02', False)
AMESaveVariable('powerSpatm@JACK02', False)
AMESaveVariable('energySpatm@JACK02', False)
AMESaveVariable('actRservo@valve01_3', False)
AMESaveVariable('powerRservo@valve01_3', False)
AMESaveVariable('energyRservo@valve01_3', False)
AMESaveVariable('actRleak@JACK03', False)
AMESaveVariable('powerRleak@JACK03', False)
AMESaveVariable('energyRleak@JACK03', False)
AMESaveVariable('actCchamber1@JACK03', False)
AMESaveVariable('powerCchamber1@JACK03', False)
AMESaveVariable('energyCchamber1@JACK03', False)
AMESaveVariable('actCchamber2@JACK03', False)
AMESaveVariable('powerCchamber2@JACK03', False)
AMESaveVariable('energyCchamber2@JACK03', False)
AMESaveVariable('actRfrict@JACK03', False)
AMESaveVariable('powerRfrict@JACK03', False)
AMESaveVariable('energyRfrict@JACK03', False)
AMESaveVariable('actCendstop@JACK03', False)
AMESaveVariable('powerCendstop@JACK03', False)
AMESaveVariable('energyCendstop@JACK03', False)
AMESaveVariable('actSpatm@JACK03', False)
AMESaveVariable('powerSpatm@JACK03', False)
AMESaveVariable('energySpatm@JACK03', False)
AMELockVariable('theta@dynamic_plmbody_5', True)

# Set run parameters
AMESetRunParameter('start_time_s', '0.00000000000000e+00')
AMESetRunParameter('stop_time_s', '5.00000000000000e+01')
AMESetRunParameter('interval_s', '5.00000000000000e-02')
AMESetRunParameter('fixed_step_s', '1.00000000000000e-03')
AMESetRunParameter('fixed_order', '1')
AMESetRunParameter('max_time_step_s', '1.00000000000000e+30')
AMESetRunParameter('tolerance', '1.00000000000000e-05')
AMESetRunParameter('integ_method', '0')
AMESetRunParameter('fixed_integ_method', '0')
AMESetRunParameter('error_type', '0')
AMESetRunParameter('solver_type', '0')
AMESetRunParameter('disable_optimized_solver', '0')
AMESetRunParameter('minimal_discontinuity_handling', '0')
AMESetRunParameter('simulation_mode', '2')
AMESetRunParameter('discontinuity_printout', '0')
AMESetRunParameter('activity_calculation', '0')
AMESetRunParameter('power_calculation', '0')
AMESetRunParameter('energy_calculation', '0')
AMESetRunParameter('hold_inputs_constant', '0')
AMESetRunParameter('lock_non_propagating_state', '0')
AMESetRunParameter('diagnotics', '0')

# Save 'HydraulicExcavator.ame' system
AMECloseCircuit(True)

# Finalize script

# Return license and close LMS Amesim Python API
AMECloseAPI()
