#------------------------------------------------------------
# Generated by LMS Amesim 14.1.0 -  45543-42458 2015.
# From "C:/Dropbox/ES/Software Campus/WaterPipe/piping_demo.ame" system,
# Created: 15.12.2017 09:42:53
#
# Note: You can copy or modify this file without restriction.
#------------------------------------------------------------



# Initializations

# Import needed modules
import os, sys

if 'ame_apy' not in sys.modules:
   try:
      from ame_apy import *
   except ImportError:
      print 'Unable to import LMS Amesim API module.\nCheck the AME environment variable.'

# Get license and initialize LMS Amesim Python API
AMEInitAPI(False)

# Create new "piping_demo" system
AMECreateCircuit('piping_demo')

# Add components

# Add "thf_fluid_data_10" component
AMEAddComponent('thf_fluid_data_10', 'thf_fluid_data_10', (30, 29))

# Set "TFFD3" submodel to "thf_fluid_data_10" component
AMEChangeSubmodel('thf_fluid_data_10', 'TFFD3', r'$AME\libthh\submodels')

# Add "hrbend" component
AMEAddComponent('hrbend', 'hrbend_0', (758, 476))

# Rotate and flip the component
AMERotateComponent('hrbend_0')
AMEMoveComponent('hrbend_0', (758, 476))

# Set "TFBP10" submodel to "hrbend" component
AMEChangeSubmodel('hrbend_0', 'TFBP10', r'$AME\libthh\submodels')

# Add "hrtee90" component
AMEAddComponent('hrtee90', 'hrtee90_0', (691, 352))

# Rotate and flip the component
AMERotateComponent('hrtee90_0')
AMERotateComponent('hrtee90_0')
AMERotateComponent('hrtee90_0')
AMEFlipComponent('hrtee90_0')
AMEMoveComponent('hrtee90_0', (691, 352))

# Set "TF3P02" submodel to "hrtee90" component
AMEChangeSubmodel('hrtee90', 'TF3P02', r'$AME\libthh\submodels')

# Add "hrbend_1" component
AMEAddComponent('hrbend', 'hrbend_1', (658, 260))

# Rotate and flip the component
AMERotateComponent('hrbend_1')
AMEMoveComponent('hrbend_1', (658, 260))

# Set "TFBP12" submodel to "hrbend_1" component
AMEChangeSubmodel('hrbend_1', 'TFBP12', r'$AME\libthh\submodels')

# Add "hrpipe" component
AMEAddComponent('hrpipe', 'hrpipe_0', (562, 244))

# Rotate and flip the component
AMEFlipComponent('hrpipe_0')
AMEMoveComponent('hrpipe_0', (562, 244))

# Set "TFL000_T" submodel to "hrpipe" component
AMEChangeSubmodel('hrpipe_0', 'TFL000_T', r'$AME\libthh\submodels')

# Add "hrbend_2" component
AMEAddComponent('hrbend', 'hrbend_2', (497, 237))

# Rotate and flip the component
AMERotateComponent('hrbend_2')
AMEMoveComponent('hrbend_2', (497, 237))

# Set "TFBP10" submodel to "hrbend_2" component
AMEChangeSubmodel('hrbend_2', 'TFBP10', r'$AME\libthh\submodels')

# Add "hrpipe_1" component
AMEAddComponent('hrpipe', 'hrpipe_1', (411, 212))

# Rotate and flip the component
AMEFlipComponent('hrpipe_1')
AMEMoveComponent('hrpipe_1', (411, 212))

# Set "TFL000_T" submodel to "hrpipe_1" component
AMEChangeSubmodel('hrpipe_1', 'TFL000_T', r'$AME\libthh\submodels')

# Add "hrbend_3" component
AMEAddComponent('hrbend', 'hrbend_3', (316, 186))

# Set "TFBP10" submodel to "hrbend_3" component
AMEChangeSubmodel('hrbend_3', 'TFBP10', r'$AME\libthh\submodels')

# Add "hrpipe_2" component
AMEAddComponent('hrpipe', 'hrpipe_2', (137, 330))

# Set "TFL001_T" submodel to "hrpipe_2" component
AMEChangeSubmodel('hrpipe_2', 'TFL001_T', r'$AME\libthh\submodels')

# Add "hrpipe_3" component
AMEAddComponent('hrpipe', 'hrpipe_3', (768, 612))

# Rotate and flip the component
AMERotateComponent('hrpipe_3')
AMERotateComponent('hrpipe_3')
AMERotateComponent('hrpipe_3')
AMEMoveComponent('hrpipe_3', (768, 612))

# Set "TFL001_T" submodel to "hrpipe_3" component
AMEChangeSubmodel('hrpipe_3', 'TFL001_T', r'$AME\libthh\submodels')

# Add "hydraulicplug" component
AMEAddComponent('hydraulicplug', 'hydraulicplug', (648, 366))

# Rotate and flip the component
AMERotateComponent('hydraulicplug')
AMEMoveComponent('hydraulicplug', (648, 366))

# Set "TFEH0" submodel to "hydraulicplug" component
AMEChangeSubmodel('hydraulicplug', 'TFEH0', r'$AME\libthh\submodels')

# Add "tank01" component
AMEAddComponent('tank01', 'tank01', (769, 667))

# Set "TFTK0" submodel to "tank01" component
AMEChangeSubmodel('tank01', 'TFTK0', r'$AME\libthh\submodels')

# Add "tank01_1" component
AMEAddComponent('tank01', 'tank01_1', (90, 332))

# Rotate and flip the component
AMERotateComponent('tank01_1')
AMEMoveComponent('tank01_1', (90, 332))

# Set "TFTK0" submodel to "tank01_1" component
AMEChangeSubmodel('tank01_1', 'TFTK0', r'$AME\libthh\submodels')

# Connect "hrbend" and "hrtee90" with a line
AMEConnectTwoPortsWithLine('hrbend_0', 0, 'hrtee90_0', 2, 'hydraulic_1', ((703, 482)))

# Connect "hrbend" and "hrpipe_3" with a line
AMEConnectTwoPortsWithLine('hrbend_0', 1, 'hrpipe_3', 0, 'hydraulic_2', ((776, 510), (774, 510)))

# Connect "hrtee90" and "hydraulicplug" with a line
AMEConnectTwoPortsWithLine('hrtee90_0', 0, 'hydraulicplug', 0, 'hydraulic_8', ((681, 364), (681, 370)))

# Connect "hrtee90" and "hrbend_1" with a line
AMEConnectTwoPortsWithLine('hrbend_1', 1, 'hrtee90_0', 1, 'hydraulic_4', ((676, 294), (703, 294)))

# Connect "hrbend_1" and "hrpipe" with a line
AMEConnectTwoPortsWithLine('hrbend_1', 0, 'hrpipe_0', 1, 'hydraulic_6', ((648, 266), (648, 250)))

# Connect "hrpipe" and "hrbend_2" with a line
AMEConnectTwoPortsWithLine('hrpipe_0', 0, 'hrbend_2', 1, 'hydraulic_7', ((552, 250), (552, 271), (515, 271)))

# Connect "hrbend_2" and "hrpipe_1" with a line
AMEConnectTwoPortsWithLine('hrbend_2', 0, 'hrpipe_1', 1, 'hydraulic', ((487, 243), (487, 218)))

# Connect "hrpipe_1" and "hrbend_3" with a line
AMEConnectTwoPortsWithLine('hrbend_3', 1, 'hrpipe_1', 0, 'hydraulic_3', ((350, 192), (350, 218)))

# Connect "hrbend_3" and "hrpipe_2" with a line
AMEConnectTwoPortsWithLine('hrbend_3', 0, 'hrpipe_2', 0, 'hydraulic_5', ((322, 336)))

# Connect "hrpipe_2" and "tank01_1" with a line
AMEConnectTwoPortsWithLine('hrpipe_2', 1, 'tank01_1', 0, 'hydraulic_10', ((127, 336), (127, 341)))

# Connect "hrpipe_3" and "tank01" with a line
AMEConnectTwoPortsWithLine('hrpipe_3', 1, 'tank01', 0, 'hydraulic_9', ((774, 646), (778, 646)))

# Set 'thf_fluid_data_10' parameters
AMESetParameterValue('aeropt@thf_fluid_data_10', '1')
AMESetParameterValue('top@thf_fluid_data_10', '2.00000000000000e+01')
AMESetParameterValue('psat@thf_fluid_data_10', '2.50000000000000e+03')
AMESetParameterValue('pvaph@thf_fluid_data_10', '5.00000000000000e-01')
AMESetParameterValue('pvapl@thf_fluid_data_10', '4.00000000000000e-01')
AMESetParameterValue('xair@thf_fluid_data_10', '1.00000000000000e-01')
AMESetParameterValue('gamma@thf_fluid_data_10', '1.40000000000000e+00')
AMESetParameterValue('muair@thf_fluid_data_10', '2.00000000000000e-02')
AMESetParameterValue('muvap@thf_fluid_data_10', '2.00000000000000e-02')
AMESetParameterValue('mvap@thf_fluid_data_10', '2.00000000000000e+02')
AMESetParameterValue('rhoair@thf_fluid_data_10', '1.20000000000000e+00')
AMESetParameterValue('cpgas@thf_fluid_data_10', '1.00400000000000e+03')
AMESetParameterValue('cpvap@thf_fluid_data_10', '1.85000000000000e+03')
AMESetParameterValue('lambdagas@thf_fluid_data_10', '2.60000000000000e-02')
AMESetParameterValue('lambdavap@thf_fluid_data_10', '1.70000000000000e-02')
AMESetParameterValue('aeratau@thf_fluid_data_10', '1.00000000000000e-03')
AMESetParameterValue('disstau@thf_fluid_data_10', '1.00000000000000e-01')
AMESetParameterValue('fi@thf_fluid_data_10', '1')
AMESetParameterValue('ftype@thf_fluid_data_10', '1')
AMESetParameterValue('sfmdb@thf_fluid_data_10', '1')
AMESetParameterValue('afmdb@thf_fluid_data_10', '1')
AMESetParameterValue('cavtype@thf_fluid_data_10', '3')
AMESetParameterValue('thhmode@thf_fluid_data_10', '1')
AMESetParameterValue('inittemp@thf_fluid_data_10', '1')
AMESetParameterValue('fluidnameTFFD1@thf_fluid_data_10', 'coolant')
AMESetParameterValue('fluidnameTFFD2@thf_fluid_data_10', 'diesel80_rme20')
AMESetParameterValue('charfileTFFD1@thf_fluid_data_10', '$AME/libthh/data/coolant.data')
AMESetParameterValue('charfileTFFD2@thf_fluid_data_10', '$AME/libthh/data_advanced/diesel80_rme20.data')
AMESetParameterValue('pvaph2T@thf_fluid_data_10', '10^(6.20963-2354.731/(280.709+T))+0.02')
AMESetParameterValue('pvapl2T@thf_fluid_data_10', '10^(6.20963-2354.731/(280.709+T))-0.02')

# Set 'hrbend' parameters
AMESetParameterValue('aeropt@hrbend_0', '1')
AMESetParameterValue('vol1@hrbend_0', '0.00000000000000e+000')
AMESetParameterValue('dvol1@hrbend_0', '0.00000000000000e+000')
AMESetParameterValue('vol2@hrbend_0', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrbend_0', '0.00000000000000e+000')
AMESetParameterValue('diam@hrbend_0', '3.00000000000000e+01')
AMESetParameterValue('delta@hrbend_0', '9.00000000000000e+01')
AMESetParameterValue('rc@hrbend_0', '6.41618708729800e+01')
AMESetParameterValue('rr@hrbend_0', '1.00000000000000e-05')
AMESetParameterValue('a0b0@hrbend_0', '1.00000000000000e+00')
AMESetParameterValue('fi@hrbend_0', '1')
AMESetParameterValue('sectiontype@hrbend_0', '1')
AMESetParameterValue('thhuse@hrbend_0', '1')

# Set 'hrtee90' parameters
AMESetParameterValue('aeropt@hrtee90_0', '1')
AMESetParameterValue('p1@hrtee90_0', '1.00000000000000e+000')
AMESetParameterValue('t1@hrtee90_0', '2.00000000000000e+001')
AMESetParameterValue('vol2@hrtee90_0', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrtee90_0', '0.00000000000000e+000')
AMESetParameterValue('p3@hrtee90_0', '1.00000000000000e+000')
AMESetParameterValue('t3@hrtee90_0', '2.00000000000000e+001')
AMESetParameterValue('xg1@hrtee90_0', '1.00000000000000e-006')
AMESetParameterValue('xu1@hrtee90_0', '1.00000000000000e-006')
AMESetParameterValue('xg3@hrtee90_0', '1.00000000000000e-006')
AMESetParameterValue('xu3@hrtee90_0', '1.00000000000000e-006')
AMESetParameterValue('diams@hrtee90_0', '1.50000000000000e+01')
AMESetParameterValue('diamc@hrtee90_0', '3.00000000000000e+01')
AMESetParameterValue('alpha@hrtee90_0', '9.00000000000000e+01')
AMESetParameterValue('relim@hrtee90_0', '1.00000000000000e+03')
AMESetParameterValue('tau@hrtee90_0', '1.00000000000000e-06')
AMESetParameterValue('x@hrtee90_0', '1.00000000000000e+00')
AMESetParameterValue('acc@hrtee90_0', '9.00000000000000e-01')
AMESetParameterValue('fi@hrtee90_0', '1')
AMESetParameterValue('mode@hrtee90_0', '1')
AMESetParameterValue('thhuse@hrtee90_0', '1')
AMESetParameterValue('aerinit@hrtee90_0', '1')
AMESetParameterValue('expsideconfig1@hrtee90_0', 'max( 0.9*(1-rq), 0.54 ) * ( 1+rq^2 - 2*(1-rq)^2 )')
AMESetParameterValue('expstraightconfig1@hrtee90_0', '1 - (1-rq)^2 - (1.4-rq)*rq^2')
AMESetParameterValue('expk31config2@hrtee90_0', '2+3*rq*(rq-1)')
AMESetParameterValue('expk21config2@hrtee90_0', '2+3*rq*(rq-1)')
AMESetParameterValue('expsideconfig3@hrtee90_0', 'max( 1-0.6*rq,  0.6 ) * ( 1+rq^2 )')
AMESetParameterValue('expstraightconfig3@hrtee90_0', 'min( 2*(2*rq-1), 0.3*(2*rq-1) ) * rq^2')
AMESetParameterValue('expsideconfig4@hrtee90_0', 'max( 0.9*(1-rq), 0.54 ) * ( 1+rq^2 -2*(1-rq)^2 )')
AMESetParameterValue('expstraightconfig4@hrtee90_0', '1 - (1-rq)^2 - (1.4-rq)*rq^2')
AMESetParameterValue('expk13config5@hrtee90_0', '1+0.3*rq^2')
AMESetParameterValue('expk12config5@hrtee90_0', '1+0.3*rq^2')
AMESetParameterValue('expsideconfig6@hrtee90_0', 'max( 1-0.6*rq,  0.6 ) * ( 1+rq^2 )')
AMESetParameterValue('expstraightconfig6@hrtee90_0', 'min( 2*(2*rq-1), 0.3*(2*rq-1) )*rq^2')

# Set 'hrbend_1' parameters
AMESetParameterValue('aeropt@hrbend_1', '1')
AMESetParameterValue('vol1@hrbend_1', '0.00000000000000e+000')
AMESetParameterValue('dvol1@hrbend_1', '0.00000000000000e+000')
AMESetParameterValue('p2@hrbend_1', '1.00000000000000e+000')
AMESetParameterValue('t2@hrbend_1', '2.00000000000000e+001')
AMESetParameterValue('xg2@hrbend_1', '1.00000000000000e-006')
AMESetParameterValue('xu2@hrbend_1', '1.00000000000000e-006')
AMESetParameterValue('diam@hrbend_1', '3.00000000000000e+01')
AMESetParameterValue('delta@hrbend_1', '9.00000000000000e+01')
AMESetParameterValue('rc@hrbend_1', '7.17600190294960e+01')
AMESetParameterValue('rr@hrbend_1', '1.00000000000000e-05')
AMESetParameterValue('a0b0@hrbend_1', '1.00000000000000e+00')
AMESetParameterValue('wallt@hrbend_1', '1.00000000000000e+01')
AMESetParameterValue('emod@hrbend_1', '2.06000000000000e+06')
AMESetParameterValue('bmeff@hrbend_1', '8.00000000000000e+03')
AMESetParameterValue('fi@hrbend_1', '1')
AMESetParameterValue('sectiontype@hrbend_1', '1')
AMESetParameterValue('thhuse@hrbend_1', '1')
AMESetParameterValue('bmind@hrbend_1', '1')
AMESetParameterValue('aerinit@hrbend_1', '1')

# Set 'hrpipe' parameters
AMESetParameterValue('aeropt@hrpipe_0', '1')
AMESetParameterValue('p1@hrpipe_0', '1.00000000000000e+000')
AMESetParameterValue('t1@hrpipe_0', '2.00000000000000e+001')
AMESetParameterValue('xg@hrpipe_0', '1.00000000000000e-006')
AMESetParameterValue('xu@hrpipe_0', '1.00000000000000e-006')
AMESetParameterValue('diam@hrpipe_0', '3.00000000000000e+01')
AMESetParameterValue('le@hrpipe_0', '5.88452570752890e-02')
AMESetParameterValue('thick@hrpipe_0', '0.00000000000000e+00')
AMESetParameterValue('emod@hrpipe_0', '2.06000000000000e+06')
AMESetParameterValue('beff@hrpipe_0', '8.00000000000000e+03')
AMESetParameterValue('kth@hrpipe_0', '0.00000000000000e+00')
AMESetParameterValue('extemp@hrpipe_0', '2.00000000000000e+01')
AMESetParameterValue('bulkfluid@hrpipe_0', '1.70000000000000e+04')
AMESetParameterValue('fi@hrpipe_0', '1')
AMESetParameterValue('method@hrpipe_0', '2')
AMESetParameterValue('thhuse@hrpipe_0', '1')
AMESetParameterValue('aerinit@hrpipe_0', '1')
AMESetParameterValue('volexptype@hrpipe_0', '1')
AMESetParameterValue('dvfile@hrpipe_0', '$AME/libthh/data/dV_P.data')
AMESetParameterValue('bmwallfile@hrpipe_0', '$AME/libthh/data/bmwall_P.data')

# Set 'hrbend_2' parameters
AMESetParameterValue('aeropt@hrbend_2', '1')
AMESetParameterValue('vol1@hrbend_2', '0.00000000000000e+000')
AMESetParameterValue('dvol1@hrbend_2', '0.00000000000000e+000')
AMESetParameterValue('vol2@hrbend_2', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrbend_2', '0.00000000000000e+000')
AMESetParameterValue('diam@hrbend_2', '3.00000000000000e+01')
AMESetParameterValue('delta@hrbend_2', '4.49999999999940e+01')
AMESetParameterValue('rc@hrbend_2', '4.99999999999990e+01')
AMESetParameterValue('rr@hrbend_2', '1.00000000000000e-05')
AMESetParameterValue('a0b0@hrbend_2', '1.00000000000000e+00')
AMESetParameterValue('fi@hrbend_2', '1')
AMESetParameterValue('sectiontype@hrbend_2', '1')
AMESetParameterValue('thhuse@hrbend_2', '1')

# Set 'hrpipe_1' parameters
AMESetParameterValue('aeropt@hrpipe_1', '1')
AMESetParameterValue('p1@hrpipe_1', '1.00000000000000e+000')
AMESetParameterValue('t1@hrpipe_1', '2.00000000000000e+001')
AMESetParameterValue('xg@hrpipe_1', '1.00000000000000e-006')
AMESetParameterValue('xu@hrpipe_1', '1.00000000000000e-006')
AMESetParameterValue('diam@hrpipe_1', '3.00000000000000e+01')
AMESetParameterValue('le@hrpipe_1', '1.09942206276770e-01')
AMESetParameterValue('thick@hrpipe_1', '0.00000000000000e+00')
AMESetParameterValue('emod@hrpipe_1', '2.06000000000000e+06')
AMESetParameterValue('beff@hrpipe_1', '8.00000000000000e+03')
AMESetParameterValue('kth@hrpipe_1', '0.00000000000000e+00')
AMESetParameterValue('extemp@hrpipe_1', '2.00000000000000e+01')
AMESetParameterValue('bulkfluid@hrpipe_1', '1.70000000000000e+04')
AMESetParameterValue('fi@hrpipe_1', '1')
AMESetParameterValue('method@hrpipe_1', '2')
AMESetParameterValue('thhuse@hrpipe_1', '1')
AMESetParameterValue('aerinit@hrpipe_1', '1')
AMESetParameterValue('volexptype@hrpipe_1', '1')
AMESetParameterValue('dvfile@hrpipe_1', '$AME/libthh/data/dV_P.data')
AMESetParameterValue('bmwallfile@hrpipe_1', '$AME/libthh/data/bmwall_P.data')

# Set 'hrbend_3' parameters
AMESetParameterValue('aeropt@hrbend_3', '1')
AMESetParameterValue('vol1@hrbend_3', '0.00000000000000e+000')
AMESetParameterValue('dvol1@hrbend_3', '0.00000000000000e+000')
AMESetParameterValue('vol2@hrbend_3', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrbend_3', '0.00000000000000e+000')
AMESetParameterValue('diam@hrbend_3', '3.00000000000000e+01')
AMESetParameterValue('delta@hrbend_3', '6.55526786290730e+01')
AMESetParameterValue('rc@hrbend_3', '4.96708809555280e+01')
AMESetParameterValue('rr@hrbend_3', '1.00000000000000e-05')
AMESetParameterValue('a0b0@hrbend_3', '1.00000000000000e+00')
AMESetParameterValue('fi@hrbend_3', '1')
AMESetParameterValue('sectiontype@hrbend_3', '1')
AMESetParameterValue('thhuse@hrbend_3', '1')

# Set 'hrpipe_2' parameters
AMESetParameterValue('aeropt@hrpipe_2', '1')
AMESetParameterValue('p1@hrpipe_2', '1.00000000000000e+000')
AMESetParameterValue('t1@hrpipe_2', '2.00000000000000e+001')
AMESetParameterValue('vol2@hrpipe_2', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrpipe_2', '0.00000000000000e+000')
AMESetParameterValue('xg1@hrpipe_2', '1.00000000000000e-006')
AMESetParameterValue('xu1@hrpipe_2', '1.00000000000000e-006')
AMESetParameterValue('diam@hrpipe_2', '2.99913947214110e+01')
AMESetParameterValue('le@hrpipe_2', '2.88018162725890e-01')
AMESetParameterValue('rr@hrpipe_2', '1.00000000000000e-05')
AMESetParameterValue('ang@hrpipe_2', '0.00000000000000e+00')
AMESetParameterValue('thick@hrpipe_2', '0.00000000000000e+00')
AMESetParameterValue('emod@hrpipe_2', '2.06000000000000e+06')
AMESetParameterValue('beff@hrpipe_2', '8.00000000000000e+03')
AMESetParameterValue('kth@hrpipe_2', '0.00000000000000e+00')
AMESetParameterValue('extemp@hrpipe_2', '2.00000000000000e+01')
AMESetParameterValue('bulkfluid@hrpipe_2', '1.70000000000000e+04')
AMESetParameterValue('fi@hrpipe_2', '1')
AMESetParameterValue('method@hrpipe_2', '2')
AMESetParameterValue('thhuse@hrpipe_2', '1')
AMESetParameterValue('aerinit@hrpipe_2', '1')
AMESetParameterValue('volexptype@hrpipe_2', '1')
AMESetParameterValue('dvfile@hrpipe_2', '$AME/libthh/data/dV_P.data')
AMESetParameterValue('bmwallfile@hrpipe_2', '$AME/libthh/data/bmwall_P.data')

# Set 'hrpipe_3' parameters
AMESetParameterValue('aeropt@hrpipe_3', '1')
AMESetParameterValue('p1@hrpipe_3', '1.00000000000000e+000')
AMESetParameterValue('t1@hrpipe_3', '2.00000000000000e+001')
AMESetParameterValue('vol2@hrpipe_3', '0.00000000000000e+000')
AMESetParameterValue('dvol2@hrpipe_3', '0.00000000000000e+000')
AMESetParameterValue('xg1@hrpipe_3', '1.00000000000000e-006')
AMESetParameterValue('xu1@hrpipe_3', '1.00000000000000e-006')
AMESetParameterValue('diam@hrpipe_3', '3.00000000000000e+01')
AMESetParameterValue('le@hrpipe_3', '1.35838129127020e-01')
AMESetParameterValue('rr@hrpipe_3', '1.00000000000000e-05')
AMESetParameterValue('ang@hrpipe_3', '0.00000000000000e+00')
AMESetParameterValue('thick@hrpipe_3', '0.00000000000000e+00')
AMESetParameterValue('emod@hrpipe_3', '2.06000000000000e+06')
AMESetParameterValue('beff@hrpipe_3', '8.00000000000000e+03')
AMESetParameterValue('kth@hrpipe_3', '0.00000000000000e+00')
AMESetParameterValue('extemp@hrpipe_3', '2.00000000000000e+01')
AMESetParameterValue('bulkfluid@hrpipe_3', '1.70000000000000e+04')
AMESetParameterValue('fi@hrpipe_3', '1')
AMESetParameterValue('method@hrpipe_3', '2')
AMESetParameterValue('thhuse@hrpipe_3', '1')
AMESetParameterValue('aerinit@hrpipe_3', '1')
AMESetParameterValue('volexptype@hrpipe_3', '1')
AMESetParameterValue('dvfile@hrpipe_3', '$AME/libthh/data/dV_P.data')
AMESetParameterValue('bmwallfile@hrpipe_3', '$AME/libthh/data/bmwall_P.data')

# Set 'hydraulicplug' parameters
AMESetParameterValue('dm1@hydraulicplug', '0.00000000000000e+000')
AMESetParameterValue('dmh1@hydraulicplug', '0.00000000000000e+000')
AMESetParameterValue('vol1@hydraulicplug', '0.00000000000000e+000')
AMESetParameterValue('dvol1@hydraulicplug', '0.00000000000000e+000')
AMESetParameterValue('flowid1@hydraulicplug', '0.00000000000000e+000')

# Set 'tank01' parameters
AMESetParameterValue('aeropt@tank01', '1')
AMESetParameterValue('p1@tank01', '1.00000000000000e+000')
AMESetParameterValue('t1@tank01', '2.00000000000000e+001')
AMESetParameterValue('nodeid1@tank01', '0.00000000000000e+000')
AMESetParameterValue('xg1@tank01', '1.00000000000000e-006')
AMESetParameterValue('xu1@tank01', '0.00000000000000e+000')
AMESetParameterValue('fi@tank01', '1')
AMESetParameterValue('thhuse@tank01', '1')

# Set 'tank01_1' parameters
AMESetParameterValue('aeropt@tank01_1', '1')
AMESetParameterValue('p1@tank01_1', '1.00000000000000e+000')
AMESetParameterValue('t1@tank01_1', '2.00000000000000e+001')
AMESetParameterValue('nodeid1@tank01_1', '0.00000000000000e+000')
AMESetParameterValue('xg1@tank01_1', '1.00000000000000e-006')
AMESetParameterValue('xu1@tank01_1', '0.00000000000000e+000')
AMESetParameterValue('fi@tank01_1', '1')
AMESetParameterValue('thhuse@tank01_1', '1')

# Set 'hydraulic' parameters

# Set 'hydraulic_1' parameters

# Set 'hydraulic_2' parameters

# Set 'hydraulic_3' parameters

# Set 'hydraulic_4' parameters

# Set 'hydraulic_5' parameters

# Set 'hydraulic_6' parameters

# Set 'hydraulic_7' parameters

# Set 'hydraulic_8' parameters

# Set 'hydraulic_9' parameters

# Set 'hydraulic_10' parameters

# Generate code
AMEGenerateCode()

# Add 'Save next' and 'Lock State' flags

# Set run parameters

# Save 'piping_demo.ame' system
AMECloseCircuit(True)

# Finalize script

# Return license and close LMS Amesim Python API
AMECloseAPI()
